# Skripsi: Integrasi Confident Learning dan CORN pada IndoBERT
## Pilot Study — Deteksi Label Noise pada Prediksi Rating Ulasan Google Play Store

**Ryan Besto Saragih — NIM 23051204205**
Pembimbing: Anita Qoiriah, S.Kom., M.Kom.

Notebook ini menjalankan pipeline lengkap pilot study sesuai Bab 1 (Subbab 1.2) dan
Bab 3 proposal: scraping → praproses → ablasi proxy classifier (P1-P4) →
deteksi noise → validasi manusia → training 6 skenario model → uji signifikansi
statistik (4 hipotesis pre-registered).

**Struktur data**: satu skema tunggal (tidak ada versioning) — `all_reviews_master.csv`
dikunci setelah scraping selesai dan dipakai sebagai sumber kebenaran tunggal untuk
seluruh eksperimen berikutnya, sesuai Batasan Masalah Bab 1.6.

**Cara pakai**: jalankan cell berurutan dari atas ke bawah. Cell scraping (Cell 3)
otomatis dilewati kalau data sudah ada — jangan hapus `all_reviews_master.csv`
kecuali memang berniat scraping ulang dari nol.

In [1]:
# ==========================================================
# CELL 2: MOUNT DRIVE + CLONE/PULL REPO
# ==========================================================
from google.colab import drive
import os, sys

drive.mount('/content/drive')

REPO_URL = "https://github.com/bestoism/skripsi-corn-label-noise"
REPO_DIR = "/content/skripsi-corn-label-noise"

if os.path.exists(REPO_DIR):
    print("🔄 Repo sudah ada, menarik update terbaru...")
    !cd {REPO_DIR} && git pull
else:
    print("⬇️  Clone repo baru...")
    !git clone {REPO_URL} {REPO_DIR}

sys.path.append(REPO_DIR)
os.chdir(REPO_DIR)
print(f"\n✅ Setup selesai. Working dir: {os.getcwd()}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
🔄 Repo sudah ada, menarik update terbaru...
Already up to date.

✅ Setup selesai. Working dir: /content/skripsi-corn-label-noise

## Instalasi Dependencies

Termasuk `py3langid` untuk filter bahasa saat scraping. Pastikan `requirements.txt`
di repo sudah memuat: `pandas`, `numpy`, `scikit-learn`, `torch`, `transformers`,
`cleanlab`, `coral-pytorch`, `statsmodels`, `scipy`, `google-play-scraper`,
`py3langid`.

In [2]:
# ==========================================================
# CELL 4: INSTALL REQUIREMENTS
# ==========================================================
!pip install -q -r requirements.txt
print("✅ Dependencies terpasang.")

✅ Dependencies terpasang.

## Import Umum
Dipakai berulang di banyak cell berikutnya — diletakkan sekali di sini supaya
tidak diulang-ulang di tiap cell.

In [3]:
# ==========================================================
# CELL 6: IMPORT UMUM
# ==========================================================
import os
import pandas as pd
import numpy as np

from src import config
print(f"📌 Proxy default aktif: [{config.PROXY_ID}] {config.PROXY_NAME}")
print(f"📁 Drive root: {config.DRIVE_ROOT}")

📌 Proxy aktif: [3] finetuned_corn — IndoBERT fine-tuned K-Fold, CORN loss (P4) -- DEFAULT/FINAL
📌 Proxy default aktif: [3] finetuned_corn
📁 Drive root: /content/drive/MyDrive/SKRIPSI_CORN

## Scraping Google Play Store

Scraping dengan filter bahasa Indonesia inline (`py3langid`), target per rating
sudah dinaikkan untuk mengantisipasi susut data sepanjang pipeline (praproses →
split → K-Fold → pruning), dan dilengkapi laporan kualitas data (distribusi
tanggal per app/rating untuk cek confound temporal, distribusi panjang teks,
deteksi teks duplikat) yang otomatis tersimpan di `results/` untuk dilampirkan
di Bab III dan Bab IV.

⚠️ **JALANKAN SEKALI SAJA SEUMUR PROYEK.** Setelah selesai, `all_reviews_master.csv`
dikunci dan dipakai sebagai sumber kebenaran tunggal. Cell ini **otomatis dilewati**
kalau file tersebut sudah ada — hapus manual hanya kalau memang sengaja ingin
scraping ulang dari nol (dan sadar semua eksperimen berikutnya perlu diulang).

Estimasi waktu: bisa 1-3 jam tergantung koneksi dan seberapa jauh Google Play
Store perlu ditelusuri untuk rating 2/3 yang jarang muncul.

In [4]:
# ==========================================================
# CELL 8: SCRAPING GOOGLE PLAY STORE (AUTO-SKIP KALAU SUDAH ADA)
# ==========================================================
from src import config

if os.path.exists(config.RAW_DATA_FILE):
    print(f"✅ {config.RAW_DATA_FILE} sudah ada -- scraping dilewati.")
    print("   Hapus file ini manual kalau memang mau scraping ulang dari nol.")
    df_check = pd.read_csv(config.RAW_DATA_FILE)
    print(f"   Baris tersedia: {len(df_check)}")
else:
    from scripts.scrape_google_play import main as run_scraping
    run_scraping()

============================================================
 GOOGLE PLAY SCRAPER — STRATIFIED PER RATING + FILTER BAHASA
============================================================

📡 SeaBank | rating=1 | target=1200 (setelah filter bahasa)
   +200 diperiksa, 167/1200 lolos filter bahasa (dibuang bahasa lain: 33)
   +200 diperiksa, 329/1200 lolos filter bahasa (dibuang bahasa lain: 71)
   +200 diperiksa, 494/1200 lolos filter bahasa (dibuang bahasa lain: 106)
   +200 diperiksa, 667/1200 lolos filter bahasa (dibuang bahasa lain: 133)
   💾 Checkpoint tersimpan (667 baris)
   +200 diperiksa, 848/1200 lolos filter bahasa (dibuang bahasa lain: 152)
   +200 diperiksa, 1011/1200 lolos filter bahasa (dibuang bahasa lain: 189)
   +200 diperiksa, 1175/1200 lolos filter bahasa (dibuang bahasa lain: 225)
   💾 Checkpoint tersimpan (1175 baris)
   +200 diperiksa, 1342/1200 lolos filter bahasa (dibuang bahasa lain: 258)
✅ Selesai: SeaBank rating=1 -> 1342 ulasan bersih [PENUH] (diperiksa: 1600, dibuang-bahasa: 258, terlalu-pendek-utk-deteksi: 13)

📡 SeaBank | rating=2 | target=900 (setelah filter bahasa)
   +200 diperiksa, 171/900 lolos filter bahasa (dibuang bahasa lain: 29)
   +200 diperiksa, 335/900 lolos filter bahasa (dibuang bahasa lain: 65)
   +200 diperiksa, 498/900 lolos filter bahasa (dibuang bahasa lain: 102)
   +200 diperiksa, 662/900 lolos filter bahasa (dibuang bahasa lain: 138)
   💾 Checkpoint tersimpan (662 baris)
   +200 diperiksa, 835/900 lolos filter bahasa (dibuang bahasa lain: 165)
   +200 diperiksa, 994/900 lolos filter bahasa (dibuang bahasa lain: 206)
✅ Selesai: SeaBank rating=2 -> 994 ulasan bersih [PENUH] (diperiksa: 1200, dibuang-bahasa: 206, terlalu-pendek-utk-deteksi: 27)

📡 SeaBank | rating=3 | target=900 (setelah filter bahasa)
   +200 diperiksa, 153/900 lolos filter bahasa (dibuang bahasa lain: 47)
   +200 diperiksa, 296/900 lolos filter bahasa (dibuang bahasa lain: 104)
   +200 diperiksa, 445/900 lolos filter bahasa (dibuang bahasa lain: 155)
   +200 diperiksa, 597/900 lolos filter bahasa (dibuang bahasa lain: 203)
   💾 Checkpoint tersimpan (597 baris)
   +200 diperiksa, 743/900 lolos filter bahasa (dibuang bahasa lain: 257)
   +200 diperiksa, 891/900 lolos filter bahasa (dibuang bahasa lain: 309)
   +200 diperiksa, 1045/900 lolos filter bahasa (dibuang bahasa lain: 355)
✅ Selesai: SeaBank rating=3 -> 1045 ulasan bersih [PENUH] (diperiksa: 1400, dibuang-bahasa: 355, terlalu-pendek-utk-deteksi: 55)

📡 SeaBank | rating=4 | target=1000 (setelah filter bahasa)
   +200 diperiksa, 128/1000 lolos filter bahasa (dibuang bahasa lain: 72)
   +200 diperiksa, 272/1000 lolos filter bahasa (dibuang bahasa lain: 128)
   +200 diperiksa, 413/1000 lolos filter bahasa (dibuang bahasa lain: 187)
   +200 diperiksa, 537/1000 lolos filter bahasa (dibuang bahasa lain: 263)
   💾 Checkpoint tersimpan (537 baris)
   +200 diperiksa, 675/1000 lolos filter bahasa (dibuang bahasa lain: 325)
   +200 diperiksa, 807/1000 lolos filter bahasa (dibuang bahasa lain: 393)
   +200 diperiksa, 948/1000 lolos filter bahasa (dibuang bahasa lain: 452)
   +200 diperiksa, 1088/1000 lolos filter bahasa (dibuang bahasa lain: 512)
   💾 Checkpoint tersimpan (1088 baris)
✅ Selesai: SeaBank rating=4 -> 1088 ulasan bersih [PENUH] (diperiksa: 1600, dibuang-bahasa: 512, terlalu-pendek-utk-deteksi: 80)

📡 SeaBank | rating=5 | target=1200 (setelah filter bahasa)
   +200 diperiksa, 127/1200 lolos filter bahasa (dibuang bahasa lain: 73)
   +200 diperiksa, 256/1200 lolos filter bahasa (dibuang bahasa lain: 144)
   +200 diperiksa, 392/1200 lolos filter bahasa (dibuang bahasa lain: 208)
   +200 diperiksa, 535/1200 lolos filter bahasa (dibuang bahasa lain: 265)
   💾 Checkpoint tersimpan (535 baris)
   +200 diperiksa, 663/1200 lolos filter bahasa (dibuang bahasa lain: 337)
   +200 diperiksa, 795/1200 lolos filter bahasa (dibuang bahasa lain: 405)
   +200 diperiksa, 925/1200 lolos filter bahasa (dibuang bahasa lain: 475)
   +200 diperiksa, 1064/1200 lolos filter bahasa (dibuang bahasa lain: 536)
   💾 Checkpoint tersimpan (1064 baris)
   +200 diperiksa, 1199/1200 lolos filter bahasa (dibuang bahasa lain: 601)
   +200 diperiksa, 1329/1200 lolos filter bahasa (dibuang bahasa lain: 671)
✅ Selesai: SeaBank rating=5 -> 1329 ulasan bersih [PENUH] (diperiksa: 2000, dibuang-bahasa: 671, terlalu-pendek-utk-deteksi: 85)
💾 SeaBank -> /content/drive/MyDrive/SKRIPSI_CORN/data/raw/SeaBank_reviews.csv

📡 Tokopedia | rating=1 | target=1200 (setelah filter bahasa)
   +200 diperiksa, 171/1200 lolos filter bahasa (dibuang bahasa lain: 29)
   +200 diperiksa, 347/1200 lolos filter bahasa (dibuang bahasa lain: 53)
   +200 diperiksa, 528/1200 lolos filter bahasa (dibuang bahasa lain: 72)
   💾 Checkpoint tersimpan (528 baris)
   +200 diperiksa, 706/1200 lolos filter bahasa (dibuang bahasa lain: 94)
   +200 diperiksa, 869/1200 lolos filter bahasa (dibuang bahasa lain: 131)
   +200 diperiksa, 1032/1200 lolos filter bahasa (dibuang bahasa lain: 168)
   💾 Checkpoint tersimpan (1032 baris)
   +200 diperiksa, 1212/1200 lolos filter bahasa (dibuang bahasa lain: 188)
✅ Selesai: Tokopedia rating=1 -> 1212 ulasan bersih [PENUH] (diperiksa: 1400, dibuang-bahasa: 188, terlalu-pendek-utk-deteksi: 0)

📡 Tokopedia | rating=2 | target=900 (setelah filter bahasa)
   +200 diperiksa, 181/900 lolos filter bahasa (dibuang bahasa lain: 19)
   +200 diperiksa, 353/900 lolos filter bahasa (dibuang bahasa lain: 47)
   +200 diperiksa, 531/900 lolos filter bahasa (dibuang bahasa lain: 69)
   💾 Checkpoint tersimpan (531 baris)
   +200 diperiksa, 704/900 lolos filter bahasa (dibuang bahasa lain: 96)
   +200 diperiksa, 883/900 lolos filter bahasa (dibuang bahasa lain: 117)
   +200 diperiksa, 1065/900 lolos filter bahasa (dibuang bahasa lain: 135)
   💾 Checkpoint tersimpan (1065 baris)
✅ Selesai: Tokopedia rating=2 -> 1065 ulasan bersih [PENUH] (diperiksa: 1200, dibuang-bahasa: 135, terlalu-pendek-utk-deteksi: 5)

📡 Tokopedia | rating=3 | target=900 (setelah filter bahasa)
   +200 diperiksa, 179/900 lolos filter bahasa (dibuang bahasa lain: 21)
   +200 diperiksa, 354/900 lolos filter bahasa (dibuang bahasa lain: 46)
   +200 diperiksa, 531/900 lolos filter bahasa (dibuang bahasa lain: 69)
   💾 Checkpoint tersimpan (531 baris)
   +200 diperiksa, 700/900 lolos filter bahasa (dibuang bahasa lain: 100)
   +200 diperiksa, 869/900 lolos filter bahasa (dibuang bahasa lain: 131)
   +200 diperiksa, 1049/900 lolos filter bahasa (dibuang bahasa lain: 151)
   💾 Checkpoint tersimpan (1049 baris)
✅ Selesai: Tokopedia rating=3 -> 1049 ulasan bersih [PENUH] (diperiksa: 1200, dibuang-bahasa: 151, terlalu-pendek-utk-deteksi: 16)

📡 Tokopedia | rating=4 | target=1000 (setelah filter bahasa)
   +200 diperiksa, 149/1000 lolos filter bahasa (dibuang bahasa lain: 51)
   +200 diperiksa, 296/1000 lolos filter bahasa (dibuang bahasa lain: 104)
   +200 diperiksa, 454/1000 lolos filter bahasa (dibuang bahasa lain: 146)
   +200 diperiksa, 603/1000 lolos filter bahasa (dibuang bahasa lain: 197)
   💾 Checkpoint tersimpan (603 baris)
   +200 diperiksa, 756/1000 lolos filter bahasa (dibuang bahasa lain: 244)
   +200 diperiksa, 912/1000 lolos filter bahasa (dibuang bahasa lain: 288)
   +200 diperiksa, 1053/1000 lolos filter bahasa (dibuang bahasa lain: 347)
✅ Selesai: Tokopedia rating=4 -> 1053 ulasan bersih [PENUH] (diperiksa: 1400, dibuang-bahasa: 347, terlalu-pendek-utk-deteksi: 42)

📡 Tokopedia | rating=5 | target=1200 (setelah filter bahasa)
   +200 diperiksa, 137/1200 lolos filter bahasa (dibuang bahasa lain: 63)
   +200 diperiksa, 269/1200 lolos filter bahasa (dibuang bahasa lain: 131)
   +200 diperiksa, 403/1200 lolos filter bahasa (dibuang bahasa lain: 197)
   +200 diperiksa, 528/1200 lolos filter bahasa (dibuang bahasa lain: 272)
   💾 Checkpoint tersimpan (528 baris)
   +200 diperiksa, 661/1200 lolos filter bahasa (dibuang bahasa lain: 339)
   +200 diperiksa, 784/1200 lolos filter bahasa (dibuang bahasa lain: 416)
   +200 diperiksa, 895/1200 lolos filter bahasa (dibuang bahasa lain: 505)
   +200 diperiksa, 1009/1200 lolos filter bahasa (dibuang bahasa lain: 591)
   +200 diperiksa, 1133/1200 lolos filter bahasa (dibuang bahasa lain: 667)
   💾 Checkpoint tersimpan (1133 baris)
   +200 diperiksa, 1255/1200 lolos filter bahasa (dibuang bahasa lain: 745)
✅ Selesai: Tokopedia rating=5 -> 1255 ulasan bersih [PENUH] (diperiksa: 2000, dibuang-bahasa: 745, terlalu-pendek-utk-deteksi: 78)
💾 Tokopedia -> /content/drive/MyDrive/SKRIPSI_CORN/data/raw/Tokopedia_reviews.csv

📡 Gojek | rating=1 | target=1200 (setelah filter bahasa)
   +200 diperiksa, 182/1200 lolos filter bahasa (dibuang bahasa lain: 18)
   +200 diperiksa, 359/1200 lolos filter bahasa (dibuang bahasa lain: 41)
   +200 diperiksa, 534/1200 lolos filter bahasa (dibuang bahasa lain: 66)
   💾 Checkpoint tersimpan (534 baris)
   +200 diperiksa, 714/1200 lolos filter bahasa (dibuang bahasa lain: 86)
   +200 diperiksa, 887/1200 lolos filter bahasa (dibuang bahasa lain: 113)
   +200 diperiksa, 1059/1200 lolos filter bahasa (dibuang bahasa lain: 141)
   💾 Checkpoint tersimpan (1059 baris)
   +200 diperiksa, 1225/1200 lolos filter bahasa (dibuang bahasa lain: 175)
✅ Selesai: Gojek rating=1 -> 1225 ulasan bersih [PENUH] (diperiksa: 1400, dibuang-bahasa: 175, terlalu-pendek-utk-deteksi: 2)

📡 Gojek | rating=2 | target=900 (setelah filter bahasa)
   +200 diperiksa, 183/900 lolos filter bahasa (dibuang bahasa lain: 17)
   +200 diperiksa, 363/900 lolos filter bahasa (dibuang bahasa lain: 37)
   +200 diperiksa, 546/900 lolos filter bahasa (dibuang bahasa lain: 54)
   💾 Checkpoint tersimpan (546 baris)
   +200 diperiksa, 731/900 lolos filter bahasa (dibuang bahasa lain: 69)
   +200 diperiksa, 917/900 lolos filter bahasa (dibuang bahasa lain: 83)
✅ Selesai: Gojek rating=2 -> 917 ulasan bersih [PENUH] (diperiksa: 1000, dibuang-bahasa: 83, terlalu-pendek-utk-deteksi: 2)

📡 Gojek | rating=3 | target=900 (setelah filter bahasa)
   +200 diperiksa, 186/900 lolos filter bahasa (dibuang bahasa lain: 14)
   +200 diperiksa, 366/900 lolos filter bahasa (dibuang bahasa lain: 34)
   +200 diperiksa, 537/900 lolos filter bahasa (dibuang bahasa lain: 63)
   💾 Checkpoint tersimpan (537 baris)
   +200 diperiksa, 717/900 lolos filter bahasa (dibuang bahasa lain: 83)
   +200 diperiksa, 901/900 lolos filter bahasa (dibuang bahasa lain: 99)
✅ Selesai: Gojek rating=3 -> 901 ulasan bersih [PENUH] (diperiksa: 1000, dibuang-bahasa: 99, terlalu-pendek-utk-deteksi: 6)

📡 Gojek | rating=4 | target=1000 (setelah filter bahasa)
   +200 diperiksa, 157/1000 lolos filter bahasa (dibuang bahasa lain: 43)
   +200 diperiksa, 302/1000 lolos filter bahasa (dibuang bahasa lain: 98)
   +200 diperiksa, 450/1000 lolos filter bahasa (dibuang bahasa lain: 150)
   +200 diperiksa, 597/1000 lolos filter bahasa (dibuang bahasa lain: 203)
   💾 Checkpoint tersimpan (597 baris)
   +200 diperiksa, 741/1000 lolos filter bahasa (dibuang bahasa lain: 259)
   +200 diperiksa, 882/1000 lolos filter bahasa (dibuang bahasa lain: 318)
   +200 diperiksa, 1035/1000 lolos filter bahasa (dibuang bahasa lain: 365)
✅ Selesai: Gojek rating=4 -> 1035 ulasan bersih [PENUH] (diperiksa: 1400, dibuang-bahasa: 365, terlalu-pendek-utk-deteksi: 63)

📡 Gojek | rating=5 | target=1200 (setelah filter bahasa)
   +200 diperiksa, 115/1200 lolos filter bahasa (dibuang bahasa lain: 85)
   +200 diperiksa, 236/1200 lolos filter bahasa (dibuang bahasa lain: 164)
   +200 diperiksa, 353/1200 lolos filter bahasa (dibuang bahasa lain: 247)
   +200 diperiksa, 471/1200 lolos filter bahasa (dibuang bahasa lain: 329)
   +200 diperiksa, 601/1200 lolos filter bahasa (dibuang bahasa lain: 399)
   💾 Checkpoint tersimpan (601 baris)
   +200 diperiksa, 727/1200 lolos filter bahasa (dibuang bahasa lain: 473)
   +200 diperiksa, 860/1200 lolos filter bahasa (dibuang bahasa lain: 540)
   +200 diperiksa, 983/1200 lolos filter bahasa (dibuang bahasa lain: 617)
   +200 diperiksa, 1111/1200 lolos filter bahasa (dibuang bahasa lain: 689)
   💾 Checkpoint tersimpan (1111 baris)
   +200 diperiksa, 1230/1200 lolos filter bahasa (dibuang bahasa lain: 770)
✅ Selesai: Gojek rating=5 -> 1230 ulasan bersih [PENUH] (diperiksa: 2000, dibuang-bahasa: 770, terlalu-pendek-utk-deteksi: 115)
💾 Gojek -> /content/drive/MyDrive/SKRIPSI_CORN/data/raw/Gojek_reviews.csv

============================================================
🎉 SELESAI! Total ulasan (setelah dedup final): 16740 (dibuang saat dedup final: 0)
📁 File master (LOCKED, jangan diubah lagi): /content/drive/MyDrive/SKRIPSI_CORN/data/raw/all_reviews_master.csv

📊 Distribusi rating keseluruhan:
rating
1    3779
2    2976
3    2995
4    3176
5    3814
Name: count, dtype: int64

📈 Distribusi rating per aplikasi:
rating         1     2     3     4     5
source_app
Gojek       1225   917   901  1035  1230
SeaBank     1342   994  1045  1088  1329
Tokopedia   1212  1065  1049  1053  1255

============================================================
 RINGKASAN SCRAPING PER (APP, RATING)
============================================================
source_app  rating  target  n_collected  n_checked  n_lang_dropped  n_too_short_for_detect status
   SeaBank       1    1200         1342       1600             258                      13  PENUH
   SeaBank       2     900          994       1200             206                      27  PENUH
   SeaBank       3     900         1045       1400             355                      55  PENUH
   SeaBank       4    1000         1088       1600             512                      80  PENUH
   SeaBank       5    1200         1329       2000             671                      85  PENUH
 Tokopedia       1    1200         1212       1400             188                       0  PENUH
 Tokopedia       2     900         1065       1200             135                       5  PENUH
 Tokopedia       3     900         1049       1200             151                      16  PENUH
 Tokopedia       4    1000         1053       1400             347                      42  PENUH
 Tokopedia       5    1200         1255       2000             745                      78  PENUH
     Gojek       1    1200         1225       1400             175                       2  PENUH
     Gojek       2     900          917       1000              83                       2  PENUH
     Gojek       3     900          901       1000              99                       6  PENUH
     Gojek       4    1000         1035       1400             365                      63  PENUH
     Gojek       5    1200         1230       2000             770                     115  PENUH

💾 Disimpan -> /content/drive/MyDrive/SKRIPSI_CORN/results/scraping_summary.csv

🌐 Filter bahasa keseluruhan: 5060/21800 (23.21%) ulasan dibuang karena terdeteksi bukan Bahasa Indonesia.
   -> Angka ini WAJIB disebutkan di Bab III (langkah pengumpulan data) sebagai
      bagian dari justifikasi kualitas data, bukan disembunyikan.

============================================================
 DISTRIBUSI TANGGAL PER (APP, RATING) -- cek confound temporal
============================================================
source_app  rating        min        max     median  count
     Gojek       1 2026-07-25 2026-09-07 2026-08-17   1225
     Gojek       2 2026-03-13 2026-09-07 2026-05-17    917
     Gojek       3 2026-02-22 2026-09-07 2026-05-04    901
     Gojek       4 2026-01-05 2026-09-07 2026-04-21   1035
     Gojek       5 2026-07-16 2026-09-07 2026-08-10   1230
   SeaBank       1 2026-07-24 2026-09-07 2026-08-09   1342
   SeaBank       2 2026-03-02 2026-09-07 2026-06-17    994
   SeaBank       3 2026-06-07 2026-09-07 2026-07-22   1045
   SeaBank       4 2026-08-01 2026-09-07 2026-08-19   1088
   SeaBank       5 2026-09-03 2026-09-07 2026-09-05   1329
 Tokopedia       1 2026-08-04 2026-09-07 2026-08-20   1212
 Tokopedia       2 2025-10-29 2026-09-07 2026-04-09   1065
 Tokopedia       3 2025-10-28 2026-09-06 2026-03-29   1049
 Tokopedia       4 2025-08-31 2026-09-07 2026-02-18   1053
 Tokopedia       5 2026-07-07 2026-09-07 2026-07-31   1255

💾 Disimpan -> /content/drive/MyDrive/SKRIPSI_CORN/results/date_distribution_per_app_rating.csv
   -> Bandingkan rentang tanggal antar rating per app secara manual.
      Kalau rating 2/3 rentangnya jauh lebih panjang ke belakang dibanding
      rating 1/4/5, itu confound temporal yang perlu disebutkan di Bab IV
      sebagai limitasi/karakteristik data (bukan wajib diperbaiki).

============================================================
 DISTRIBUSI PANJANG TEKS ULASAN (dalam kata)
============================================================
count    16740.000000
mean        15.139904
std         16.364271
min          1.000000
10%          1.000000
25%          4.000000
50%          9.000000
75%         21.000000
90%         37.000000
max         97.000000

Ulasan sangat pendek (<=3 kata): 24.61%
   -> Ulasan pendek TIDAK dibuang otomatis (kurang informasi != label
      noise), tapi angka ini perlu dicatat di Bab IV supaya deteksi noise
      pada ulasan pendek tidak salah ditafsirkan sebagai mismatch rating-teks.

============================================================
 DETEKSI TEKS DUPLIKAT PERSIS (indikasi template/spam)
============================================================
Baris yang teksnya persis sama dengan >=1 baris lain: 2832 (16.92%)

Top 20 teks paling sering berulang:
review_text
bagus                     649
ok                        464
baik                      297
sangat membantu           209
sangat bagus              107
sangat baik               101
sangat puas                64
terbaik                    56
👍                          48
sangat memuaskan           33
senang                     30
bagus sekali               26
cukup baik                 24
membantu                   21
Ok                         17
sangat membantu sekali     16
sangat senang              15
mudah dan cepat            15
sangat bermanfaat          14
sangat mudah               14

💾 Disimpan -> /content/drive/MyDrive/SKRIPSI_CORN/results/duplicate_review_texts.csv
   -> Ini HANYA duplikat persis sama (bukan near-duplicate/typo-variant).
      Kalau porsinya besar, pertimbangkan cek manual di Bab IV apakah ada
      pola bot/template yang perlu dibahas sebagai limitasi data.

============================================================
📝 CATATAN UNTUK BAB 3 (Batasan/Langkah Penelitian):
   Data diambil pada: 2026-09-08
   - Kalau target rating 2/3 tidak tercapai, itu wajar (rating tengah
     memang lebih jarang muncul secara alami) -- laporkan apa adanya.
   - Sertakan angka filter bahasa (lihat scraping_summary.csv) sebagai
     bagian dari deskripsi langkah pengumpulan data.
   - Sertakan distribusi tanggal per (app, rating) di Bab IV sebagai
     pembahasan karakteristik/limitasi data (confound temporal).
============================================================

## Kunci Korpus + EDA Awal (SEBELUM Praproses)
Dijalankan sekali di atas korpus mentah: dedup review_id, kunci sumber
kebenaran tunggal (manifest + SHA-256, Batasan Masalah butir 7), dan
seluruh angka deskripsi data Subbab III.B (filter bahasa, distribusi
tanggal, panjang teks, duplikat, konflik teks-rating, cek overlap split).

In [5]:
# ==========================================================
# CELL 9: KUNCI KORPUS + EDA AWAL
# ==========================================================
from scripts.eda_dataset import main as run_eda
run_eda()

====================================================================
 EDA DAN PENGUNCIAN DATASET
====================================================================

====================================================================
 0. MUAT DAN KUNCI KORPUS MENTAH
====================================================================
Baris mentah dibaca            : 16740
Setelah dedup review_id       : 16740 (dibuang 0)
Setelah buang teks kosong      : 16740 (dibuang 0)
Rentang tanggal                : 2025-08-31 s.d. 2026-09-07

====================================================================
 1. DISTRIBUSI RATING
====================================================================
           n  persen
rating
1       3779   22.57
2       2976   17.78
3       2995   17.89
4       3176   18.97
5       3814   22.78
   -> /content/drive/MyDrive/SKRIPSI_CORN/results/eda/01_distribusi_rating_keseluruhan.csv

Per aplikasi:
rating         1     2     3     4     5
source_app
Gojek       1225   917   901  1035  1230
SeaBank     1342   994  1045  1088  1329
Tokopedia   1212  1065  1049  1053  1255
   -> /content/drive/MyDrive/SKRIPSI_CORN/results/eda/01_distribusi_rating_per_aplikasi.csv
   -> /content/drive/MyDrive/SKRIPSI_CORN/results/eda/01_distribusi_rating_per_aplikasi.png

Catatan Bab IV: distribusi ini hasil kuota per rating, BUKAN
distribusi alami Play Store. Sebutkan eksplisit agar angka MAE/QWK
absolut tidak salah dibaca sebagai performa pada distribusi lapangan.

====================================================================
 2. DISTRIBUSI TANGGAL PER (APLIKASI, RATING) -- CONFOUND TEMPORAL
====================================================================
source_app  rating    n tanggal_min tanggal_median tanggal_max  rentang_hari
     Gojek       1 1225  2026-07-25     2026-08-17  2026-09-07            44
     Gojek       2  917  2026-03-13     2026-05-17  2026-09-07           178
     Gojek       3  901  2026-02-22     2026-05-04  2026-09-07           197
     Gojek       4 1035  2026-01-05     2026-04-21  2026-09-07           245
     Gojek       5 1230  2026-07-16     2026-08-10  2026-09-07            53
   SeaBank       1 1342  2026-07-24     2026-08-09  2026-09-07            45
   SeaBank       2  994  2026-03-02     2026-06-17  2026-09-07           189
   SeaBank       3 1045  2026-06-07     2026-07-22  2026-09-07            92
   SeaBank       4 1088  2026-08-01     2026-08-19  2026-09-07            37
   SeaBank       5 1329  2026-09-03     2026-09-05  2026-09-07             4
 Tokopedia       1 1212  2026-08-04     2026-08-20  2026-09-07            34
 Tokopedia       2 1065  2025-10-29     2026-04-09  2026-09-07           313
 Tokopedia       3 1049  2025-10-28     2026-03-29  2026-09-06           313
 Tokopedia       4 1053  2025-08-31     2026-02-18  2026-09-07           372
 Tokopedia       5 1255  2026-07-07     2026-07-31  2026-09-07            62
   -> /content/drive/MyDrive/SKRIPSI_CORN/results/eda/02_distribusi_tanggal_per_app_rating.csv

Keparahan confound temporal per aplikasi (selisih rentang hari terpanjang vs terpendek antar rating):
  Gojek       : rating 4 mundur 245 hari, rating 1 hanya 44 hari (selisih 201 hari)
  SeaBank     : rating 2 mundur 189 hari, rating 5 hanya 4 hari (selisih 185 hari)
  Tokopedia   : rating 4 mundur 372 hari, rating 1 hanya 34 hari (selisih 338 hari)
   -> /content/drive/MyDrive/SKRIPSI_CORN/results/eda/02_rentang_tanggal_per_rating.png

Hipotesis yang dicek di sini: karena Sort.NEWEST digabung
filter_score_with, rating yang lebih jarang (2 dan 3) harus ditelusuri
lebih jauh ke belakang untuk memenuhi kuota, sehingga rentangnya lebih
panjang dan median tanggalnya lebih tua. Kalau pola itu terlihat,
laporkan sebagai confound temporal di Bab IV (tidak dikoreksi via
resampling, sesuai Batasan Masalah butir 7).

====================================================================
 3. DISTRIBUSI PANJANG TEKS ULASAN
====================================================================
         n_kata  n_karakter
count  16740.00    16740.00
mean      15.14       94.09
std       16.36      102.17
min        1.00        1.00
10%        1.00        7.00
25%        4.00       23.00
50%        9.00       59.00
75%       21.00      128.00
90%       37.00      229.00
95%       51.00      313.00
99%       77.00      492.00
max       97.00      500.00
   -> /content/drive/MyDrive/SKRIPSI_CORN/results/eda/03_ringkasan_panjang_teks.csv

Panjang teks (kata) per rating:
        count   mean  median    std
rating
1        3779  21.24    16.0  17.62
2        2976  20.72    16.0  17.59
3        2995  16.65    12.0  16.11
4        3176  10.82     6.0  14.03
5        3814   7.15     4.0  10.79
   -> /content/drive/MyDrive/SKRIPSI_CORN/results/eda/03_panjang_teks_per_rating.csv

Ulasan sangat pendek (<= 3 kata): 4119 baris (24.61%)
Persentase per rating:
rating
1     6.43
2     8.87
3    18.06
4    37.56
5    49.24
   -> /content/drive/MyDrive/SKRIPSI_CORN/results/eda/03_teks_sangat_pendek_per_rating.csv

Ulasan > 100 kata (perkiraan kasar risiko truncation MAX_LEN=128): 0.00%
   -> /content/drive/MyDrive/SKRIPSI_CORN/results/eda/03_histogram_panjang_teks.png

Catatan Bab IV: ulasan pendek TIDAK dibuang. Angka ini dipakai agar
deteksi noise pada ulasan pendek tidak salah ditafsirkan sebagai
ketidaksesuaian rating-teks, padahal informasinya memang minim.

====================================================================
 4. TEKS DUPLIKAT PERSIS (indikasi template / spam)
====================================================================
Grup teks yang muncul >1 kali : 201
Baris yang terlibat           : 2832 (16.92%)

20 teks paling sering berulang:
                  teks  jumlah
                 bagus     649
                    ok     464
                  baik     297
       sangat membantu     209
          sangat bagus     107
           sangat baik     101
           sangat puas      64
               terbaik      56
                     👍      48
      sangat memuaskan      33
                senang      30
          bagus sekali      26
            cukup baik      24
              membantu      21
                    Ok      17
sangat membantu sekali      16
         sangat senang      15
       mudah dan cepat      15
     sangat bermanfaat      14
          sangat mudah      14
   -> /content/drive/MyDrive/SKRIPSI_CORN/results/eda/04_teks_duplikat_persis_top200.csv

Keterbatasan: ini HANYA duplikat persis sama. Near-duplicate
(beda satu typo atau spasi) tidak tertangkap -- sebutkan di Bab IV
kalau angka ini dipakai sebagai bukti keberadaan template/spam.

====================================================================
 5. TEKS IDENTIK DENGAN RATING BERBEDA (ambiguitas natural)
====================================================================
Grup teks dengan rating berbeda : 138
Baris yang terlibat             : 2688 (16.06%)

Sebaran selisih rating maksimum per grup:
selisih_rating_maks_dalam_grup
1    68
2    34
3    17
4    19
   -> /content/drive/MyDrive/SKRIPSI_CORN/results/eda/05_konflik_sebaran_selisih_rating.csv

Grup yang seri (tidak ada rating mayoritas): 57 grup, 155 baris
-> Grup seri dibuang seluruhnya oleh resolusi voting mayoritas
   (III.D butir 8). Angka ini memperkirakan susut datanya.
   -> /content/drive/MyDrive/SKRIPSI_CORN/results/eda/05_contoh_teks_konflik_rating.csv

Catatan Bab IV: angka ini adalah bukti kuantitatif awal adanya
ambiguitas natural pada data, SEBELUM deteksi noise formal dijalankan.

====================================================================
 6. OVERLAP TEKS LINTAS SPLIT LATIH-UJI (risiko kebocoran)
====================================================================
Simulasi split stratified 80:20 (random_state=42)
  Baris latih : 13392
  Baris uji   : 3348
  Baris uji yang teksnya JUGA muncul di data latih: 555 (16.58%)
    - dengan rating identik  : 521
    - dengan rating berbeda  : 1857

Aturan keputusan:
  <1 %  -> pertahankan split acak, laporkan angkanya, tambahkan
           pemeriksaan ketahanan pada subset uji tanpa kembaran.
  1-3 % -> masih bisa dipertahankan, tapi pemeriksaan ketahanan wajib.
  >3 %  -> pindah ke grouped split berbasis hash teks, agar semua
           baris berteks identik jatuh ke sisi split yang sama.
   -> /content/drive/MyDrive/SKRIPSI_CORN/results/eda/06_overlap_teks_lintas_split.csv

====================================================================
 7. PENGUNCIAN KORPUS (MANIFEST)
====================================================================
{
  "locked_at": "2026-09-08 06:19:53",
  "master_file": "/content/drive/MyDrive/SKRIPSI_CORN/data/raw/all_reviews_master.csv",
  "sha256": "c589b92cbe2fbc34d67e43a0a866a281cb31603a190af4517ef7f157e54589f6",
  "n_rows_final": 16740,
  "date_min": "2025-08-31",
  "date_max": "2026-09-07",
  "apps": [
    "Gojek",
    "SeaBank",
    "Tokopedia"
  ],
  "rating_counts": {
    "1": 3779,
    "2": 2976,
    "3": 2995,
    "4": 3176,
    "5": 3814
  },
  "load_stats": {
    "n_raw": 16740,
    "n_after_review_id_dedup": 16740,
    "n_after_empty_text_removal": 16740
  },
  "eda_stats": {
    "n_dup_groups": 201,
    "n_dup_rows": 2832,
    "pct_dup_rows": 16.92,
    "n_conflict_groups": 138,
    "n_conflict_rows": 2688,
    "pct_conflict_rows": 16.06,
    "n_test_leaked": 555,
    "pct_test_leaked": 16.58
  },
  "split_config": {
    "test_size": 0.2,
    "random_state": 42
  }
}

-> /content/drive/MyDrive/SKRIPSI_CORN/results/dataset_manifest.json

MULAI SEKARANG file master TIDAK BOLEH DIUBAH LAGI.
Commit manifest ini ke git bersama hash-nya. Kalau di kemudian hari
hash file master tidak cocok dengan manifest, berarti korpus berubah
dan seluruh hasil eksperimen harus dijalankan ulang.

====================================================================
 SELESAI
====================================================================
Semua tabel dan gambar tersimpan di: /content/drive/MyDrive/SKRIPSI_CORN/results/eda

Yang langsung bisa masuk proposal:
  III.B butir 1 -> angka filter bahasa (dari scraping_summary.csv)
  III.B butir 2 -> 02_distribusi_tanggal_per_app_rating.csv
  III.B butir 3 -> 03_ringkasan_panjang_teks.csv
  III.B butir 4 -> 04_teks_duplikat_persis_top200.csv
  III.D butir 7 -> 05_konflik_sebaran_selisih_rating.csv
  III.E         -> 06_overlap_teks_lintas_split.csv

## Praproses Teks

Case folding, penghapusan URL/username, translasi emoji ke sentimen (kamus
diperluas), normalisasi elongasi huruf, normalisasi slang (Kamus Alay + kamus
domain, dengan perbaikan pencocokan token bertanda-baca), resolusi konflik
teks-identik-rating-berbeda (voting mayoritas), dan penghapusan duplikat murni.

Preprocessing dijaga minimal (tanpa stemming/stopword removal) sesuai rekomendasi
untuk model berbasis BERT (Wilie dkk. 2020; Koto dkk. 2020).

⚠️ **JALANKAN SEKALI SAJA.** Split train/test yang dihasilkan (`split_train_raw.csv`
/ `split_test.csv`) dikunci dan dipakai di seluruh eksperimen berikutnya, termasuk
pilot study proxy P1-P4. Cell ini otomatis dilewati kalau split sudah ada.

In [6]:
# ==========================================================
# CELL 10: PREPROCESSING + SPLIT 70:10:20 GROUPED-STRATIFIED
# ==========================================================
from src.preprocess import run_preprocessing
from src.data_split import create_splits
from src import config

if os.path.exists(config.TRAIN_RAW_FILE) and os.path.exists(config.VAL_FILE) and os.path.exists(config.TEST_FILE):
    print("✅ Split train/val/test sudah ada -- dilewati.")
    df_train = pd.read_csv(config.TRAIN_RAW_FILE)
    df_val = pd.read_csv(config.VAL_FILE)
    df_test = pd.read_csv(config.TEST_FILE)
    print(f"   Train: {len(df_train)} | Val: {len(df_val)} | Test: {len(df_test)}")
else:
    print("=" * 60); print(" PREPROCESSING "); print("=" * 60)
    df_clean = run_preprocessing(config.RAW_DATA_FILE, config.CLEAN_TEXT_FILE)
    df_clean = df_clean.dropna(subset=["cleaned_text", "rating"])

    print("\n" + "=" * 60)
    print(" SPLIT 70:10:20 (grouped berdasarkan teks, stratified rating, seed=42) ")
    print("=" * 60)
    df_train, df_val, df_test = create_splits(config.CLEAN_TEXT_FILE, seed=42)

⬇️  Mengunduh Kamus Alay (Salsabila dkk., 2018) dari https://raw.githubusercontent.com/nasalsabila/kamus-alay/master/colloquial-indonesian-lexicon.csv ...
✅ Tersimpan di cache: /content/drive/MyDrive/SKRIPSI_CORN/lexicon/slang_base.csv
📖 Kamus slang dasar: 15006 entri (Salsabila dkk., 2018)
============================================================
 PREPROCESSING
============================================================
📥 Membaca data mentah dari: /content/drive/MyDrive/SKRIPSI_CORN/data/raw/all_reviews_master.csv
📏 Jumlah data awal: 16740 baris
🧹 Cleaning teks (lowercase, URL/tag, emoji, elongasi, slang)...
📊 Cakupan kamus slang (estimasi dari raw text): 29410/253442 kata (11.6%)
📏 Distribusi panjang teks: median=10 kata, ulasan sangat pendek (<=3 kata): 24.40%
🔍 Teks identik, rating berbeda: 151 kasus
   -> Resolusi (voting mayoritas) BELUM dieksekusi di sini. Sesuai Subbab
      III.D butir 8, resolusi dijalankan di clean.py SETELAH deteksi
      Confident Learning, agar baris ini turut dianalisis CL sebagai kandidat noise.
✅ Setelah dibersihkan: 14221 baris (terbuang: 2519)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/1.53k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/229k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

✂️  Ulasan yang token-nya terpotong (> 128 token): 0.06%
💾 Disimpan di: /content/drive/MyDrive/SKRIPSI_CORN/data/processed/reviews_clean.csv

============================================================
 SPLIT 70:10:20 (grouped berdasarkan teks, stratified rating, seed=42)
============================================================
📦 Jumlah teks unik: 13979 (dari 14221 baris)
✅ Train: 9949 baris (70.0%)
✅ Val  : 1416 baris (10.0%)
✅ Test : 2856 baris (20.1%)

📎 Baris yang terlibat pengelompokan teks duplikat: 393 (2.76%) -- dijamin satu sisi split (Subbab III.E).
   Distribusi rating Train: {1: 0.262, 2: 0.201, 3: 0.188, 4: 0.169, 5: 0.18}
   Distribusi rating Val: {1: 0.263, 2: 0.201, 3: 0.186, 4: 0.167, 5: 0.182}
   Distribusi rating Test: {1: 0.261, 2: 0.201, 3: 0.188, 4: 0.169, 5: 0.182}

## Pilot Study — Ablasi Proxy Classifier (P1-P4)

Menjalankan Confident Learning untuk 4 dari 5 tahap ablasi proxy classifier
(Tabel 3.2, Bab 3): P1 (CLS embedding beku + LR), P2 (mean-pooling beku + LR),
P3 (IndoBERT fine-tuned, Cross-Entropy), P4 (IndoBERT fine-tuned, CORN — proxy
final). P5 (fusi sentimen eksternal) dijalankan terpisah di Cell berikutnya
karena butuh model sentimen tambahan dan bukan bagian pilot study Bab 1.

Setiap proxy sekarang: (a) memakai skema K-Fold yang identik (shuffle=True,
seed=42) untuk P1/P2 maupun P3/P4, (b) dikalibrasi lewat temperature scaling
untuk P3/P4, (c) metode filter cleanlab dipilih otomatis lewat kriteria
eksplisit (paling dekat dengan estimasi teoretis `num_label_issues()`), bukan
hardcode.

Hasilnya terkumpul di `results/proxy_ablation_table.csv` — inilah **Tabel 1.1**
pilot study di Bab 1 proposal.

⏱️ P3 dan P4 butuh fine-tuning K-Fold (5 fold × 3 epoch masing-masing) — cell
ini bisa memakan waktu cukup lama.

In [7]:
# ==========================================================
# CELL 12: PILOT STUDY -- ABLASI PROXY P1-P4
# ==========================================================
import pandas as pd
from src import config
from src.clean import run_confident_learning

PILOT_PROXY_IDS = [0, 1, 2, 3]  # P5 (fusion, id 4) dijalankan terpisah di Cell 14

for pid in PILOT_PROXY_IDS:
    print(f"\n{'='*70}\n PILOT STUDY -- PROXY_ID = {pid} \n{'='*70}")
    config.set_proxy(pid)
    try:
        run_confident_learning()
    except Exception as e:
        print(f"⚠️ Proxy {pid} gagal: {e}")
        continue

print("\n✅ Pilot study (P1-P4) selesai.")
pilot_table = pd.read_csv(config.PROXY_QUALITY_LOG_FILE)
display(pilot_table)

======================================================================
 PILOT STUDY -- PROXY_ID = 0
======================================================================
📌 Proxy aktif: [0] frozen_cls_lr — CLS embedding beku + Logistic Regression (P1)
============================================================
 CONFIDENT LEARNING — proxy aktif: [0] frozen_cls_lr
============================================================
📥 Memuat 9949 baris data train.

🧮 Menghitung OOF pred_probs — proxy [0] frozen_cls_lr

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  498MB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  498MB

model.safetensors: downloading bytes:           |  0.00B

Embedding (cls):   0%|          | 0/622 [00:00<?, ?it/s]

Embedding (cls):   0%|          | 1/622 [00:00<05:23,  1.92it/s]

Embedding (cls):   0%|          | 3/622 [00:00<02:05,  4.92it/s]

Embedding (cls):   1%|          | 5/622 [00:00<01:21,  7.54it/s]

Embedding (cls):   1%|          | 7/622 [00:00<01:05,  9.33it/s]

Embedding (cls):   1%|▏         | 9/622 [00:01<01:00, 10.18it/s]

Embedding (cls):   2%|▏         | 11/622 [00:01<00:54, 11.27it/s]

Embedding (cls):   2%|▏         | 13/622 [00:01<00:54, 11.16it/s]

Embedding (cls):   2%|▏         | 15/622 [00:01<00:50, 11.95it/s]

Embedding (cls):   3%|▎         | 17/622 [00:01<00:51, 11.79it/s]

Embedding (cls):   3%|▎         | 19/622 [00:01<00:46, 12.89it/s]

Embedding (cls):   3%|▎         | 21/622 [00:02<00:52, 11.52it/s]

Embedding (cls):   4%|▎         | 23/622 [00:02<00:52, 11.44it/s]

Embedding (cls):   4%|▍         | 25/622 [00:02<00:52, 11.29it/s]

Embedding (cls):   4%|▍         | 27/622 [00:02<00:51, 11.62it/s]

Embedding (cls):   5%|▍         | 29/622 [00:02<00:48, 12.17it/s]

Embedding (cls):   5%|▍         | 31/622 [00:02<00:46, 12.73it/s]

Embedding (cls):   5%|▌         | 33/622 [00:03<00:41, 14.14it/s]

Embedding (cls):   6%|▌         | 35/622 [00:03<00:43, 13.65it/s]

Embedding (cls):   6%|▌         | 37/622 [00:03<00:38, 15.07it/s]

Embedding (cls):   6%|▋         | 39/622 [00:03<00:39, 14.68it/s]

Embedding (cls):   7%|▋         | 41/622 [00:03<00:37, 15.49it/s]

Embedding (cls):   7%|▋         | 43/622 [00:03<00:35, 16.11it/s]

Embedding (cls):   7%|▋         | 46/622 [00:03<00:29, 19.45it/s]

Embedding (cls):   8%|▊         | 49/622 [00:03<00:26, 21.33it/s]

Embedding (cls):   8%|▊         | 52/622 [00:04<00:29, 19.03it/s]

Embedding (cls):   9%|▉         | 55/622 [00:04<00:31, 18.02it/s]

Embedding (cls):   9%|▉         | 57/622 [00:04<00:32, 17.42it/s]

Embedding (cls):   9%|▉         | 59/622 [00:04<00:33, 16.73it/s]

Embedding (cls):  10%|▉         | 61/622 [00:04<00:32, 17.34it/s]

Embedding (cls):  10%|█         | 63/622 [00:04<00:31, 17.55it/s]

Embedding (cls):  11%|█         | 66/622 [00:04<00:28, 19.60it/s]

Embedding (cls):  11%|█         | 68/622 [00:04<00:29, 19.04it/s]

Embedding (cls):  11%|█▏        | 70/622 [00:05<00:29, 18.65it/s]

Embedding (cls):  12%|█▏        | 72/622 [00:05<00:29, 18.85it/s]

Embedding (cls):  12%|█▏        | 74/622 [00:05<00:32, 16.97it/s]

Embedding (cls):  12%|█▏        | 76/622 [00:05<00:30, 17.72it/s]

Embedding (cls):  13%|█▎        | 78/622 [00:05<00:29, 18.15it/s]

Embedding (cls):  13%|█▎        | 81/622 [00:05<00:26, 20.10it/s]

Embedding (cls):  14%|█▎        | 84/622 [00:05<00:30, 17.65it/s]

Embedding (cls):  14%|█▍        | 86/622 [00:05<00:30, 17.43it/s]

Embedding (cls):  14%|█▍        | 88/622 [00:06<00:30, 17.37it/s]

Embedding (cls):  14%|█▍        | 90/622 [00:06<00:31, 16.69it/s]

Embedding (cls):  15%|█▍        | 92/622 [00:06<00:31, 17.06it/s]

Embedding (cls):  15%|█▌        | 94/622 [00:06<00:29, 17.80it/s]

Embedding (cls):  15%|█▌        | 96/622 [00:06<00:29, 18.07it/s]

Embedding (cls):  16%|█▌        | 99/622 [00:06<00:25, 20.13it/s]

Embedding (cls):  16%|█▋        | 102/622 [00:06<00:23, 22.50it/s]

Embedding (cls):  17%|█▋        | 106/622 [00:06<00:19, 26.49it/s]

Embedding (cls):  18%|█▊        | 109/622 [00:07<00:19, 26.92it/s]

Embedding (cls):  18%|█▊        | 113/622 [00:07<00:18, 28.22it/s]

Embedding (cls):  19%|█▊        | 116/622 [00:07<00:21, 23.83it/s]

Embedding (cls):  19%|█▉        | 119/622 [00:07<00:21, 22.87it/s]

Embedding (cls):  20%|█▉        | 122/622 [00:07<00:21, 23.71it/s]

Embedding (cls):  20%|██        | 125/622 [00:07<00:21, 23.39it/s]

Embedding (cls):  21%|██        | 128/622 [00:07<00:23, 21.12it/s]

Embedding (cls):  21%|██        | 131/622 [00:07<00:22, 22.15it/s]

Embedding (cls):  22%|██▏       | 134/622 [00:08<00:22, 21.23it/s]

Embedding (cls):  22%|██▏       | 138/622 [00:08<00:19, 24.39it/s]

Embedding (cls):  23%|██▎       | 141/622 [00:08<00:19, 24.49it/s]

Embedding (cls):  23%|██▎       | 145/622 [00:08<00:17, 26.74it/s]

Embedding (cls):  24%|██▍       | 148/622 [00:08<00:20, 22.99it/s]

Embedding (cls):  24%|██▍       | 151/622 [00:08<00:19, 24.39it/s]

Embedding (cls):  25%|██▍       | 154/622 [00:08<00:18, 24.78it/s]

Embedding (cls):  25%|██▌       | 158/622 [00:09<00:18, 25.52it/s]

Embedding (cls):  26%|██▌       | 161/622 [00:09<00:18, 24.62it/s]

Embedding (cls):  26%|██▋       | 164/622 [00:09<00:22, 20.43it/s]

Embedding (cls):  27%|██▋       | 167/622 [00:09<00:21, 21.21it/s]

Embedding (cls):  27%|██▋       | 170/622 [00:09<00:22, 20.23it/s]

Embedding (cls):  28%|██▊       | 173/622 [00:09<00:23, 19.52it/s]

Embedding (cls):  28%|██▊       | 176/622 [00:10<00:23, 18.64it/s]

Embedding (cls):  29%|██▉       | 180/622 [00:10<00:21, 20.40it/s]

Embedding (cls):  30%|██▉       | 184/622 [00:10<00:18, 24.21it/s]

Embedding (cls):  30%|███       | 187/622 [00:10<00:17, 24.62it/s]

Embedding (cls):  31%|███       | 190/622 [00:10<00:19, 21.62it/s]

Embedding (cls):  31%|███       | 194/622 [00:10<00:18, 22.68it/s]

Embedding (cls):  32%|███▏      | 197/622 [00:11<00:22, 18.70it/s]

Embedding (cls):  32%|███▏      | 200/622 [00:11<00:25, 16.84it/s]

Embedding (cls):  32%|███▏      | 202/622 [00:11<00:25, 16.54it/s]

Embedding (cls):  33%|███▎      | 204/622 [00:11<00:25, 16.26it/s]

Embedding (cls):  33%|███▎      | 206/622 [00:11<00:25, 16.61it/s]

Embedding (cls):  33%|███▎      | 208/622 [00:11<00:27, 15.06it/s]

Embedding (cls):  34%|███▍      | 210/622 [00:11<00:26, 15.45it/s]

Embedding (cls):  34%|███▍      | 212/622 [00:12<00:25, 15.81it/s]

Embedding (cls):  34%|███▍      | 214/622 [00:12<00:26, 15.55it/s]

Embedding (cls):  35%|███▍      | 216/622 [00:12<00:25, 16.15it/s]

Embedding (cls):  35%|███▌      | 218/622 [00:12<00:24, 16.19it/s]

Embedding (cls):  35%|███▌      | 220/622 [00:12<00:24, 16.30it/s]

Embedding (cls):  36%|███▌      | 222/622 [00:12<00:24, 16.42it/s]

Embedding (cls):  36%|███▌      | 224/622 [00:12<00:25, 15.70it/s]

Embedding (cls):  36%|███▋      | 226/622 [00:12<00:23, 16.58it/s]

Embedding (cls):  37%|███▋      | 229/622 [00:13<00:21, 18.39it/s]

Embedding (cls):  37%|███▋      | 231/622 [00:13<00:21, 17.79it/s]

Embedding (cls):  37%|███▋      | 233/622 [00:13<00:21, 17.91it/s]

Embedding (cls):  38%|███▊      | 236/622 [00:13<00:21, 18.25it/s]

Embedding (cls):  38%|███▊      | 238/622 [00:13<00:22, 17.39it/s]

Embedding (cls):  39%|███▊      | 240/622 [00:13<00:22, 16.97it/s]

Embedding (cls):  39%|███▉      | 242/622 [00:13<00:24, 15.52it/s]

Embedding (cls):  39%|███▉      | 244/622 [00:13<00:24, 15.70it/s]

Embedding (cls):  40%|███▉      | 246/622 [00:14<00:23, 15.68it/s]

Embedding (cls):  40%|███▉      | 248/622 [00:14<00:24, 15.02it/s]

Embedding (cls):  40%|████      | 250/622 [00:14<00:25, 14.66it/s]

Embedding (cls):  41%|████      | 252/622 [00:14<00:24, 14.95it/s]

Embedding (cls):  41%|████      | 254/622 [00:14<00:26, 14.06it/s]

Embedding (cls):  41%|████      | 256/622 [00:14<00:27, 13.51it/s]

Embedding (cls):  41%|████▏     | 258/622 [00:14<00:24, 14.75it/s]

Embedding (cls):  42%|████▏     | 260/622 [00:15<00:24, 14.63it/s]

Embedding (cls):  42%|████▏     | 262/622 [00:15<00:23, 15.08it/s]

Embedding (cls):  42%|████▏     | 264/622 [00:15<00:24, 14.75it/s]

Embedding (cls):  43%|████▎     | 266/622 [00:15<00:26, 13.66it/s]

Embedding (cls):  43%|████▎     | 268/622 [00:15<00:23, 14.82it/s]

Embedding (cls):  43%|████▎     | 270/622 [00:15<00:22, 15.32it/s]

Embedding (cls):  44%|████▎     | 272/622 [00:15<00:24, 14.45it/s]

Embedding (cls):  44%|████▍     | 274/622 [00:16<00:24, 14.29it/s]

Embedding (cls):  44%|████▍     | 276/622 [00:16<00:23, 14.93it/s]

Embedding (cls):  45%|████▍     | 278/622 [00:16<00:24, 14.32it/s]

Embedding (cls):  45%|████▌     | 280/622 [00:16<00:23, 14.68it/s]

Embedding (cls):  45%|████▌     | 282/622 [00:16<00:23, 14.21it/s]

Embedding (cls):  46%|████▌     | 284/622 [00:16<00:24, 13.72it/s]

Embedding (cls):  46%|████▌     | 286/622 [00:16<00:23, 14.25it/s]

Embedding (cls):  46%|████▋     | 288/622 [00:17<00:23, 14.03it/s]

Embedding (cls):  47%|████▋     | 290/622 [00:17<00:24, 13.49it/s]

Embedding (cls):  47%|████▋     | 292/622 [00:17<00:24, 13.63it/s]

Embedding (cls):  47%|████▋     | 294/622 [00:17<00:21, 15.06it/s]

Embedding (cls):  48%|████▊     | 296/622 [00:17<00:22, 14.70it/s]

Embedding (cls):  48%|████▊     | 298/622 [00:17<00:20, 15.55it/s]

Embedding (cls):  48%|████▊     | 301/622 [00:17<00:18, 17.31it/s]

Embedding (cls):  49%|████▊     | 303/622 [00:17<00:19, 16.68it/s]

Embedding (cls):  49%|████▉     | 305/622 [00:18<00:19, 16.36it/s]

Embedding (cls):  49%|████▉     | 307/622 [00:18<00:19, 15.77it/s]

Embedding (cls):  50%|████▉     | 309/622 [00:18<00:19, 15.92it/s]

Embedding (cls):  50%|█████     | 311/622 [00:18<00:21, 14.74it/s]

Embedding (cls):  50%|█████     | 313/622 [00:18<00:21, 14.49it/s]

Embedding (cls):  51%|█████     | 316/622 [00:18<00:19, 15.76it/s]

Embedding (cls):  51%|█████     | 318/622 [00:18<00:19, 15.70it/s]

Embedding (cls):  51%|█████▏    | 320/622 [00:19<00:18, 16.24it/s]

Embedding (cls):  52%|█████▏    | 323/622 [00:19<00:17, 17.13it/s]

Embedding (cls):  52%|█████▏    | 325/622 [00:19<00:17, 17.17it/s]

Embedding (cls):  53%|█████▎    | 327/622 [00:19<00:16, 17.56it/s]

Embedding (cls):  53%|█████▎    | 329/622 [00:19<00:17, 17.12it/s]

Embedding (cls):  53%|█████▎    | 331/622 [00:19<00:17, 16.87it/s]

Embedding (cls):  54%|█████▎    | 333/622 [00:19<00:17, 16.53it/s]

Embedding (cls):  54%|█████▍    | 336/622 [00:19<00:16, 16.91it/s]

Embedding (cls):  54%|█████▍    | 338/622 [00:20<00:16, 17.39it/s]

Embedding (cls):  55%|█████▍    | 341/622 [00:20<00:15, 17.85it/s]

Embedding (cls):  55%|█████▌    | 343/622 [00:20<00:15, 18.18it/s]

Embedding (cls):  55%|█████▌    | 345/622 [00:20<00:15, 17.69it/s]

Embedding (cls):  56%|█████▌    | 347/622 [00:20<00:16, 16.65it/s]

Embedding (cls):  56%|█████▋    | 350/622 [00:20<00:14, 18.79it/s]

Embedding (cls):  57%|█████▋    | 353/622 [00:20<00:14, 18.60it/s]

Embedding (cls):  57%|█████▋    | 355/622 [00:21<00:15, 17.35it/s]

Embedding (cls):  57%|█████▋    | 357/622 [00:21<00:15, 17.42it/s]

Embedding (cls):  58%|█████▊    | 360/622 [00:21<00:13, 19.18it/s]

Embedding (cls):  58%|█████▊    | 362/622 [00:21<00:14, 17.65it/s]

Embedding (cls):  59%|█████▊    | 364/622 [00:21<00:15, 16.73it/s]

Embedding (cls):  59%|█████▉    | 366/622 [00:21<00:15, 16.55it/s]

Embedding (cls):  59%|█████▉    | 369/622 [00:21<00:13, 19.38it/s]

Embedding (cls):  60%|█████▉    | 371/622 [00:21<00:13, 18.07it/s]

Embedding (cls):  60%|█████▉    | 373/622 [00:22<00:15, 16.59it/s]

Embedding (cls):  60%|██████    | 376/622 [00:22<00:13, 18.92it/s]

Embedding (cls):  61%|██████    | 378/622 [00:22<00:12, 19.11it/s]

Embedding (cls):  61%|██████    | 380/622 [00:22<00:13, 18.27it/s]

Embedding (cls):  62%|██████▏   | 383/622 [00:22<00:12, 19.87it/s]

Embedding (cls):  62%|██████▏   | 386/622 [00:22<00:12, 19.48it/s]

Embedding (cls):  63%|██████▎   | 389/622 [00:22<00:11, 20.68it/s]

Embedding (cls):  63%|██████▎   | 392/622 [00:22<00:10, 22.60it/s]

Embedding (cls):  64%|██████▎   | 395/622 [00:23<00:09, 22.81it/s]

Embedding (cls):  64%|██████▍   | 398/622 [00:23<00:11, 20.36it/s]

Embedding (cls):  64%|██████▍   | 401/622 [00:23<00:09, 22.33it/s]

Embedding (cls):  65%|██████▍   | 404/622 [00:23<00:09, 23.48it/s]

Embedding (cls):  65%|██████▌   | 407/622 [00:23<00:09, 21.75it/s]

Embedding (cls):  66%|██████▌   | 410/622 [00:23<00:10, 20.78it/s]

Embedding (cls):  66%|██████▋   | 413/622 [00:23<00:09, 21.11it/s]

Embedding (cls):  67%|██████▋   | 416/622 [00:24<00:12, 16.82it/s]

Embedding (cls):  67%|██████▋   | 418/622 [00:24<00:13, 15.59it/s]

Embedding (cls):  68%|██████▊   | 420/622 [00:24<00:13, 15.45it/s]

Embedding (cls):  68%|██████▊   | 422/622 [00:24<00:12, 15.93it/s]

Embedding (cls):  68%|██████▊   | 424/622 [00:24<00:13, 14.30it/s]

Embedding (cls):  68%|██████▊   | 426/622 [00:24<00:14, 13.79it/s]

Embedding (cls):  69%|██████▉   | 428/622 [00:25<00:12, 14.98it/s]

Embedding (cls):  69%|██████▉   | 430/622 [00:25<00:13, 14.60it/s]

Embedding (cls):  69%|██████▉   | 432/622 [00:25<00:13, 14.09it/s]

Embedding (cls):  70%|██████▉   | 434/622 [00:25<00:14, 13.36it/s]

Embedding (cls):  70%|███████   | 436/622 [00:25<00:14, 13.20it/s]

Embedding (cls):  70%|███████   | 438/622 [00:25<00:14, 13.08it/s]

Embedding (cls):  71%|███████   | 440/622 [00:25<00:13, 13.88it/s]

Embedding (cls):  71%|███████   | 442/622 [00:26<00:12, 14.21it/s]

Embedding (cls):  71%|███████▏  | 444/622 [00:26<00:12, 14.68it/s]

Embedding (cls):  72%|███████▏  | 446/622 [00:26<00:12, 13.95it/s]

Embedding (cls):  72%|███████▏  | 448/622 [00:26<00:12, 13.52it/s]

Embedding (cls):  72%|███████▏  | 450/622 [00:26<00:13, 13.16it/s]

Embedding (cls):  73%|███████▎  | 452/622 [00:26<00:12, 13.70it/s]

Embedding (cls):  73%|███████▎  | 454/622 [00:26<00:12, 12.93it/s]

Embedding (cls):  73%|███████▎  | 456/622 [00:27<00:12, 13.23it/s]

Embedding (cls):  74%|███████▎  | 458/622 [00:27<00:13, 12.08it/s]

Embedding (cls):  74%|███████▍  | 460/622 [00:27<00:13, 11.83it/s]

Embedding (cls):  74%|███████▍  | 462/622 [00:27<00:13, 12.11it/s]

Embedding (cls):  75%|███████▍  | 464/622 [00:27<00:11, 13.44it/s]

Embedding (cls):  75%|███████▍  | 466/622 [00:27<00:11, 13.50it/s]

Embedding (cls):  75%|███████▌  | 469/622 [00:28<00:10, 15.12it/s]

Embedding (cls):  76%|███████▌  | 471/622 [00:28<00:10, 14.06it/s]

Embedding (cls):  76%|███████▌  | 473/622 [00:28<00:09, 14.96it/s]

Embedding (cls):  76%|███████▋  | 475/622 [00:28<00:10, 14.11it/s]

Embedding (cls):  77%|███████▋  | 477/622 [00:28<00:10, 13.54it/s]

Embedding (cls):  77%|███████▋  | 479/622 [00:28<00:10, 13.66it/s]

Embedding (cls):  77%|███████▋  | 481/622 [00:28<00:10, 13.02it/s]

Embedding (cls):  78%|███████▊  | 483/622 [00:29<00:10, 13.12it/s]

Embedding (cls):  78%|███████▊  | 485/622 [00:29<00:10, 12.60it/s]

Embedding (cls):  78%|███████▊  | 487/622 [00:29<00:10, 12.86it/s]

Embedding (cls):  79%|███████▊  | 489/622 [00:29<00:11, 12.06it/s]

Embedding (cls):  79%|███████▉  | 491/622 [00:29<00:11, 11.86it/s]

Embedding (cls):  79%|███████▉  | 493/622 [00:30<00:11, 11.43it/s]

Embedding (cls):  80%|███████▉  | 495/622 [00:30<00:10, 11.86it/s]

Embedding (cls):  80%|███████▉  | 497/622 [00:30<00:10, 12.05it/s]

Embedding (cls):  80%|████████  | 499/622 [00:30<00:09, 12.80it/s]

Embedding (cls):  81%|████████  | 501/622 [00:30<00:08, 14.30it/s]

Embedding (cls):  81%|████████  | 503/622 [00:30<00:08, 13.78it/s]

Embedding (cls):  81%|████████▏ | 506/622 [00:30<00:07, 14.53it/s]

Embedding (cls):  82%|████████▏ | 508/622 [00:31<00:08, 14.14it/s]

Embedding (cls):  82%|████████▏ | 510/622 [00:31<00:08, 13.63it/s]

Embedding (cls):  82%|████████▏ | 512/622 [00:31<00:07, 14.64it/s]

Embedding (cls):  83%|████████▎ | 514/622 [00:31<00:06, 15.56it/s]

Embedding (cls):  83%|████████▎ | 516/622 [00:31<00:06, 15.22it/s]

Embedding (cls):  83%|████████▎ | 518/622 [00:31<00:06, 14.86it/s]

Embedding (cls):  84%|████████▎ | 520/622 [00:31<00:06, 15.39it/s]

Embedding (cls):  84%|████████▍ | 522/622 [00:31<00:06, 15.34it/s]

Embedding (cls):  84%|████████▍ | 524/622 [00:32<00:06, 15.32it/s]

Embedding (cls):  85%|████████▍ | 526/622 [00:32<00:06, 14.01it/s]

Embedding (cls):  85%|████████▍ | 528/622 [00:32<00:06, 15.19it/s]

Embedding (cls):  85%|████████▌ | 530/622 [00:32<00:06, 14.72it/s]

Embedding (cls):  86%|████████▌ | 532/622 [00:32<00:06, 13.23it/s]

Embedding (cls):  86%|████████▌ | 534/622 [00:32<00:06, 13.16it/s]

Embedding (cls):  86%|████████▌ | 536/622 [00:33<00:06, 12.60it/s]

Embedding (cls):  86%|████████▋ | 538/622 [00:33<00:06, 13.57it/s]

Embedding (cls):  87%|████████▋ | 540/622 [00:33<00:06, 13.12it/s]

Embedding (cls):  87%|████████▋ | 542/622 [00:33<00:05, 13.89it/s]

Embedding (cls):  87%|████████▋ | 544/622 [00:33<00:05, 14.69it/s]

Embedding (cls):  88%|████████▊ | 546/622 [00:33<00:05, 14.37it/s]

Embedding (cls):  88%|████████▊ | 548/622 [00:33<00:04, 15.02it/s]

Embedding (cls):  88%|████████▊ | 550/622 [00:33<00:05, 13.76it/s]

Embedding (cls):  89%|████████▊ | 552/622 [00:34<00:05, 13.59it/s]

Embedding (cls):  89%|████████▉ | 554/622 [00:34<00:04, 14.92it/s]

Embedding (cls):  89%|████████▉ | 556/622 [00:34<00:04, 14.63it/s]

Embedding (cls):  90%|████████▉ | 558/622 [00:34<00:04, 14.76it/s]

Embedding (cls):  90%|█████████ | 560/622 [00:34<00:04, 13.03it/s]

Embedding (cls):  90%|█████████ | 562/622 [00:34<00:04, 13.78it/s]

Embedding (cls):  91%|█████████ | 564/622 [00:35<00:04, 12.96it/s]

Embedding (cls):  91%|█████████ | 566/622 [00:35<00:04, 13.66it/s]

Embedding (cls):  91%|█████████▏| 568/622 [00:35<00:04, 13.31it/s]

Embedding (cls):  92%|█████████▏| 571/622 [00:35<00:03, 15.44it/s]

Embedding (cls):  92%|█████████▏| 573/622 [00:35<00:02, 16.43it/s]

Embedding (cls):  92%|█████████▏| 575/622 [00:35<00:02, 16.30it/s]

Embedding (cls):  93%|█████████▎| 577/622 [00:35<00:02, 15.18it/s]

Embedding (cls):  93%|█████████▎| 579/622 [00:36<00:03, 14.09it/s]

Embedding (cls):  93%|█████████▎| 581/622 [00:36<00:02, 14.25it/s]

Embedding (cls):  94%|█████████▎| 583/622 [00:36<00:02, 14.01it/s]

Embedding (cls):  94%|█████████▍| 585/622 [00:36<00:02, 13.85it/s]

Embedding (cls):  95%|█████████▍| 588/622 [00:36<00:02, 15.73it/s]

Embedding (cls):  95%|█████████▍| 590/622 [00:36<00:01, 16.04it/s]

Embedding (cls):  95%|█████████▌| 592/622 [00:36<00:01, 16.94it/s]

Embedding (cls):  96%|█████████▌| 595/622 [00:36<00:01, 18.23it/s]

Embedding (cls):  96%|█████████▌| 597/622 [00:37<00:01, 16.71it/s]

Embedding (cls):  96%|█████████▋| 599/622 [00:37<00:01, 16.86it/s]

Embedding (cls):  97%|█████████▋| 602/622 [00:37<00:01, 19.44it/s]

Embedding (cls):  97%|█████████▋| 605/622 [00:37<00:00, 22.04it/s]

Embedding (cls):  98%|█████████▊| 609/622 [00:37<00:00, 23.61it/s]

Embedding (cls):  98%|█████████▊| 612/622 [00:37<00:00, 21.14it/s]

Embedding (cls):  99%|█████████▉| 615/622 [00:37<00:00, 22.71it/s]

Embedding (cls):  99%|█████████▉| 618/622 [00:38<00:00, 22.23it/s]

Embedding (cls): 100%|██████████| 622/622 [00:38<00:00, 16.27it/s]

📐 Kualitas proxy [frozen_cls_lr]:
   Exact Accuracy : 0.4290
   MAE            : 0.9471
   Off-by-1 Acc   : 0.7450
   QWK            : 0.6108

🔎 Analisis Metode Filter Cleanlab:
   'confident_learning': 4578 baris diflag (46.01%)
   'prune_by_noise_rate': 3950 baris diflag (39.70%)

🎯 Pemilihan metode filter (kriteria: paling dekat dengan estimasi teoretis terkalibrasi):
   Estimasi teoretis (num_label_issues, off_diagonal_calibrated) : 5752 baris
   'confident_learning': 4578 baris (selisih: 1174) <-- DIPILIH
   'prune_by_noise_rate': 3950 baris (selisih: 1802)

✅ Deteksi selesai (metode terpilih: confident_learning).

📊 Distribusi rating_diff pada baris noise (sebelum resolusi):
rating_diff
1    2564
2    1300
3     537
4     177
Name: count, dtype: int64
🗑️  Baris dibuang (rating minoritas dalam grup konflik): 0
🗑️  Baris dibuang (tie, tidak ada mayoritas jelas): 263
   Total dibuang: 263

🗳️  Resolusi konflik teks-identik (voting mayoritas, PASCA-deteksi CL): 9949 -> 9686 baris (dibuang 263)
   Raw (resolved, baseline)     : 9686
   Hard-prune     : buang 4441 / sisa 5245
   Severity-aware : buang 1936 / sisa 7750
📄 Tabel ablasi proxy diperbarui -> /content/drive/MyDrive/SKRIPSI_CORN/results/proxy_ablation_table.csv

💾 Raw (resolved) -> /content/drive/MyDrive/SKRIPSI_CORN/cleaned/train_resolved.csv
💾 Cleaned (hard)   -> /content/drive/MyDrive/SKRIPSI_CORN/cleaned/train_cleaned_hard__frozen_cls_lr.csv
💾 Cleaned (severe) -> /content/drive/MyDrive/SKRIPSI_CORN/cleaned/train_cleaned_severe__frozen_cls_lr.csv

📝 Sample validasi manusia (100 baris, BUTA -- predicted_rating/rating_diff TIDAK disertakan):
   /content/drive/MyDrive/SKRIPSI_CORN/human_validation/human_validation_sample__frozen_cls_lr.csv
   (referensi internal untuk breakdown per-bin -> /content/drive/MyDrive/SKRIPSI_CORN/human_validation/human_validation_internal__frozen_cls_lr.csv)
   Distribusi rating_diff (internal): {1: 55, 2: 15, 3: 15, 4: 15}
   -> Isi kolom 'human_verdict' manual, lalu jalankan src.human_validation.compute_agreement()

======================================================================
 PILOT STUDY -- PROXY_ID = 1
======================================================================
📌 Proxy aktif: [1] frozen_meanpool_lr — Mean-pooling embedding beku + Logistic Regression (P2)
============================================================
 CONFIDENT LEARNING — proxy aktif: [1] frozen_meanpool_lr
============================================================
📥 Memuat 9949 baris data train.

🧮 Menghitung OOF pred_probs — proxy [1] frozen_meanpool_lr

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Embedding (mean): 100%|██████████| 622/622 [00:42<00:00, 14.59it/s]

📐 Kualitas proxy [frozen_meanpool_lr]:
   Exact Accuracy : 0.4293
   MAE            : 0.9594
   Off-by-1 Acc   : 0.7403
   QWK            : 0.5995

🔎 Analisis Metode Filter Cleanlab:
   'confident_learning': 4600 baris diflag (46.24%)
   'prune_by_noise_rate': 3954 baris diflag (39.74%)

🎯 Pemilihan metode filter (kriteria: paling dekat dengan estimasi teoretis terkalibrasi):
   Estimasi teoretis (num_label_issues, off_diagonal_calibrated) : 5724 baris
   'confident_learning': 4600 baris (selisih: 1124) <-- DIPILIH
   'prune_by_noise_rate': 3954 baris (selisih: 1770)

✅ Deteksi selesai (metode terpilih: confident_learning).

📊 Distribusi rating_diff pada baris noise (sebelum resolusi):
rating_diff
1    2554
2    1274
3     558
4     214
Name: count, dtype: int64
🗑️  Baris dibuang (rating minoritas dalam grup konflik): 0
🗑️  Baris dibuang (tie, tidak ada mayoritas jelas): 263
   Total dibuang: 263

🗳️  Resolusi konflik teks-identik (voting mayoritas, PASCA-deteksi CL): 9949 -> 9686 baris (dibuang 263)
   Raw (resolved, baseline)     : 9686
   Hard-prune     : buang 4445 / sisa 5241
   Severity-aware : buang 1960 / sisa 7726
📄 Tabel ablasi proxy diperbarui -> /content/drive/MyDrive/SKRIPSI_CORN/results/proxy_ablation_table.csv

💾 Raw (resolved) -> /content/drive/MyDrive/SKRIPSI_CORN/cleaned/train_resolved.csv
💾 Cleaned (hard)   -> /content/drive/MyDrive/SKRIPSI_CORN/cleaned/train_cleaned_hard__frozen_meanpool_lr.csv
💾 Cleaned (severe) -> /content/drive/MyDrive/SKRIPSI_CORN/cleaned/train_cleaned_severe__frozen_meanpool_lr.csv

📝 Sample validasi manusia (100 baris, BUTA -- predicted_rating/rating_diff TIDAK disertakan):
   /content/drive/MyDrive/SKRIPSI_CORN/human_validation/human_validation_sample__frozen_meanpool_lr.csv
   (referensi internal untuk breakdown per-bin -> /content/drive/MyDrive/SKRIPSI_CORN/human_validation/human_validation_internal__frozen_meanpool_lr.csv)
   Distribusi rating_diff (internal): {1: 55, 2: 15, 3: 15, 4: 15}
   -> Isi kolom 'human_verdict' manual, lalu jalankan src.human_validation.compute_agreement()

======================================================================
 PILOT STUDY -- PROXY_ID = 2
======================================================================
📌 Proxy aktif: [2] finetuned_ce — IndoBERT fine-tuned K-Fold, CE loss (P3)
============================================================
 CONFIDENT LEARNING — proxy aktif: [2] finetuned_ce
============================================================
📥 Memuat 9949 baris data train.

🧮 Menghitung OOF pred_probs — proxy [2] finetuned_ce
   [Proxy finetuned_ce] Fold 1/5 (train=7959, val=1990)...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

      Epoch 1/3 - Loss: 1.3168
      Epoch 2/3 - Loss: 1.1566
      Epoch 3/3 - Loss: 0.9859
   🌡️  Temperature scaling [finetuned_ce]: T=1.2510 (NLL 1.3569 -> 1.3017)
   [Proxy finetuned_ce] Fold 2/5 (train=7959, val=1990)...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

      Epoch 1/3 - Loss: 1.3139
      Epoch 2/3 - Loss: 1.1494
      Epoch 3/3 - Loss: 0.9668
   🌡️  Temperature scaling [finetuned_ce]: T=1.2624 (NLL 1.3297 -> 1.2651)
   [Proxy finetuned_ce] Fold 3/5 (train=7959, val=1990)...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

      Epoch 1/3 - Loss: 1.3173
      Epoch 2/3 - Loss: 1.1539
      Epoch 3/3 - Loss: 0.9646
   🌡️  Temperature scaling [finetuned_ce]: T=1.2579 (NLL 1.3377 -> 1.2759)
   [Proxy finetuned_ce] Fold 4/5 (train=7959, val=1990)...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

      Epoch 1/3 - Loss: 1.3131
      Epoch 2/3 - Loss: 1.1536
      Epoch 3/3 - Loss: 0.9817
   🌡️  Temperature scaling [finetuned_ce]: T=1.1994 (NLL 1.2580 -> 1.2278)
   [Proxy finetuned_ce] Fold 5/5 (train=7960, val=1989)...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

      Epoch 1/3 - Loss: 1.3274
      Epoch 2/3 - Loss: 1.1613
      Epoch 3/3 - Loss: 0.9725
   🌡️  Temperature scaling [finetuned_ce]: T=1.2604 (NLL 1.3414 -> 1.2795)
   🌡️  Temperature per fold [finetuned_ce]: ['1.251', '1.262', '1.258', '1.199', '1.260'] (mean=1.246)

📐 Kualitas proxy [finetuned_ce]:
   Exact Accuracy : 0.4546
   MAE            : 0.7858
   Off-by-1 Acc   : 0.8204
   QWK            : 0.6713

🔎 Analisis Metode Filter Cleanlab:
   'confident_learning': 4857 baris diflag (48.82%)
   'prune_by_noise_rate': 4372 baris diflag (43.94%)

🎯 Pemilihan metode filter (kriteria: paling dekat dengan estimasi teoretis terkalibrasi):
   Estimasi teoretis (num_label_issues, off_diagonal_calibrated) : 5506 baris
   'confident_learning': 4857 baris (selisih: 649) <-- DIPILIH
   'prune_by_noise_rate': 4372 baris (selisih: 1134)

✅ Deteksi selesai (metode terpilih: confident_learning).

📊 Distribusi rating_diff pada baris noise (sebelum resolusi):
rating_diff
1    3265
2    1203
3     295
4      94
Name: count, dtype: int64
🗑️  Baris dibuang (rating minoritas dalam grup konflik): 0
🗑️  Baris dibuang (tie, tidak ada mayoritas jelas): 263
   Total dibuang: 263

🗳️  Resolusi konflik teks-identik (voting mayoritas, PASCA-deteksi CL): 9949 -> 9686 baris (dibuang 263)
   Raw (resolved, baseline)     : 9686
   Hard-prune     : buang 4724 / sisa 4962
   Severity-aware : buang 1541 / sisa 8145
📄 Tabel ablasi proxy diperbarui -> /content/drive/MyDrive/SKRIPSI_CORN/results/proxy_ablation_table.csv

💾 Raw (resolved) -> /content/drive/MyDrive/SKRIPSI_CORN/cleaned/train_resolved.csv
💾 Cleaned (hard)   -> /content/drive/MyDrive/SKRIPSI_CORN/cleaned/train_cleaned_hard__finetuned_ce.csv
💾 Cleaned (severe) -> /content/drive/MyDrive/SKRIPSI_CORN/cleaned/train_cleaned_severe__finetuned_ce.csv

📝 Sample validasi manusia (100 baris, BUTA -- predicted_rating/rating_diff TIDAK disertakan):
   /content/drive/MyDrive/SKRIPSI_CORN/human_validation/human_validation_sample__finetuned_ce.csv
   (referensi internal untuk breakdown per-bin -> /content/drive/MyDrive/SKRIPSI_CORN/human_validation/human_validation_internal__finetuned_ce.csv)
   Distribusi rating_diff (internal): {1: 55, 2: 15, 3: 15, 4: 15}
   -> Isi kolom 'human_verdict' manual, lalu jalankan src.human_validation.compute_agreement()

======================================================================
 PILOT STUDY -- PROXY_ID = 3
======================================================================
📌 Proxy aktif: [3] finetuned_corn — IndoBERT fine-tuned K-Fold, CORN loss (P4) -- DEFAULT/FINAL
============================================================
 CONFIDENT LEARNING — proxy aktif: [3] finetuned_corn
============================================================
📥 Memuat 9949 baris data train.

🧮 Menghitung OOF pred_probs — proxy [3] finetuned_corn
   [Proxy finetuned_corn] Fold 1/5 (train=7959, val=1990)...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

      Epoch 1/3 - Loss: 0.5074
      Epoch 2/3 - Loss: 0.4435
      Epoch 3/3 - Loss: 0.3732
   🌡️  Temperature scaling [finetuned_corn]: T=1.2129 (NLL 1.3526 -> 1.3107)
   [Proxy finetuned_corn] Fold 2/5 (train=7959, val=1990)...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

      Epoch 1/3 - Loss: 0.5062
      Epoch 2/3 - Loss: 0.4434
      Epoch 3/3 - Loss: 0.3760
   🌡️  Temperature scaling [finetuned_corn]: T=1.1565 (NLL 1.2668 -> 1.2472)
   [Proxy finetuned_corn] Fold 3/5 (train=7959, val=1990)...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

      Epoch 1/3 - Loss: 0.5090
      Epoch 2/3 - Loss: 0.4447
      Epoch 3/3 - Loss: 0.3757
   🌡️  Temperature scaling [finetuned_corn]: T=1.2170 (NLL 1.3391 -> 1.2936)
   [Proxy finetuned_corn] Fold 4/5 (train=7959, val=1990)...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

      Epoch 1/3 - Loss: 0.5087
      Epoch 2/3 - Loss: 0.4437
      Epoch 3/3 - Loss: 0.3754
   🌡️  Temperature scaling [finetuned_corn]: T=1.1666 (NLL 1.3101 -> 1.2867)
   [Proxy finetuned_corn] Fold 5/5 (train=7960, val=1989)...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

      Epoch 1/3 - Loss: 0.5069
      Epoch 2/3 - Loss: 0.4423
      Epoch 3/3 - Loss: 0.3715
   🌡️  Temperature scaling [finetuned_corn]: T=1.1582 (NLL 1.3178 -> 1.2959)
   🌡️  Temperature per fold [finetuned_corn]: ['1.213', '1.156', '1.217', '1.167', '1.158'] (mean=1.182)

📐 Kualitas proxy [finetuned_corn]:
   Exact Accuracy : 0.4596
   MAE            : 0.7939
   Off-by-1 Acc   : 0.8142
   QWK            : 0.6713

🔎 Analisis Metode Filter Cleanlab:
   'confident_learning': 4732 baris diflag (47.56%)
   'prune_by_noise_rate': 4236 baris diflag (42.58%)

🎯 Pemilihan metode filter (kriteria: paling dekat dengan estimasi teoretis terkalibrasi):
   Estimasi teoretis (num_label_issues, off_diagonal_calibrated) : 5441 baris
   'confident_learning': 4732 baris (selisih: 709) <-- DIPILIH
   'prune_by_noise_rate': 4236 baris (selisih: 1205)

✅ Deteksi selesai (metode terpilih: confident_learning).

📊 Distribusi rating_diff pada baris noise (sebelum resolusi):
rating_diff
1    3093
2    1198
3     340
4     101
Name: count, dtype: int64
🗑️  Baris dibuang (rating minoritas dalam grup konflik): 0
🗑️  Baris dibuang (tie, tidak ada mayoritas jelas): 263
   Total dibuang: 263

🗳️  Resolusi konflik teks-identik (voting mayoritas, PASCA-deteksi CL): 9949 -> 9686 baris (dibuang 263)
   Raw (resolved, baseline)     : 9686
   Hard-prune     : buang 4583 / sisa 5103
   Severity-aware : buang 1560 / sisa 8126
📄 Tabel ablasi proxy diperbarui -> /content/drive/MyDrive/SKRIPSI_CORN/results/proxy_ablation_table.csv

💾 Raw (resolved) -> /content/drive/MyDrive/SKRIPSI_CORN/cleaned/train_resolved.csv
💾 Cleaned (hard)   -> /content/drive/MyDrive/SKRIPSI_CORN/cleaned/train_cleaned_hard__finetuned_corn.csv
💾 Cleaned (severe) -> /content/drive/MyDrive/SKRIPSI_CORN/cleaned/train_cleaned_severe__finetuned_corn.csv

📝 Sample validasi manusia (100 baris, BUTA -- predicted_rating/rating_diff TIDAK disertakan):
   /content/drive/MyDrive/SKRIPSI_CORN/human_validation/human_validation_sample__finetuned_corn.csv
   (referensi internal untuk breakdown per-bin -> /content/drive/MyDrive/SKRIPSI_CORN/human_validation/human_validation_internal__finetuned_corn.csv)
   Distribusi rating_diff (internal): {1: 55, 2: 15, 3: 15, 4: 15}
   -> Isi kolom 'human_verdict' manual, lalu jalankan src.human_validation.compute_agreement()

✅ Pilot study (P1-P4) selesai.

,proxy_id,proxy_name,proxy_desc,accuracy,mae,off_by_one,qwk,pct_flagged_noise,selected_filter_method,n_issues_confident_learning,n_issues_prune_by_noise_rate,n_issues_estimated_theoretical
0,0,frozen_cls_lr,CLS embedding beku + Logistic Regression (P1),0.428988,0.947130,0.744999,0.610804,46.014675,confident_learning,4578,3950,5752
1,1,frozen_meanpool_lr,Mean-pooling embedding beku + Logistic Regress...,0.429289,0.959393,0.740275,0.599542,46.235803,confident_learning,4600,3954,5724
2,2,finetuned_ce,"IndoBERT fine-tuned K-Fold, CE loss (P3)",0.454619,0.785808,0.820384,0.671313,48.818977,confident_learning,4857,4372,5506
3,3,finetuned_corn,"IndoBERT fine-tuned K-Fold, CORN loss (P4) -- ...",0.459644,0.793949,0.814152,0.671262,47.562569,confident_learning,4732,4236,5441

## Kunci Proxy Final (P4) + Ekspor Sample Validasi Manusia

Menjalankan ulang Confident Learning dengan proxy final terkunci (P4/CORN,
sesuai skema integrasi ketat Bab 1.1) — akan memuat dari cache kalau sudah
pernah dihitung di Cell 12, jadi cepat. Ini menghasilkan sample 50 baris
(stratified by rating_diff) untuk validasi manusia.

⚠️ **BERHENTI setelah cell ini** — isi dulu `human_verdict` secara manual
sebelum lanjut ke Cell 17.

In [8]:
# ==========================================================
# CELL 16: KUNCI PROXY FINAL (P4) -- WAJIB SEBELUM VALIDASI MANUSIA
# ==========================================================
from src import config

config.set_proxy(3)
print(f"🔒 Proxy final terkunci: [{config.PROXY_ID}] {config.PROXY_NAME}")

from src.clean import run_confident_learning
df_noise, proxy_metrics = run_confident_learning()

print("ℹ️  Resolusi konflik teks-identik-rating-beda sekarang otomatis dieksekusi")
print("   di dalam run_confident_learning() SETELAH deteksi CL (Subbab III.D butir 8).")

print("\n⚠️  BERHENTI DI SINI SEBELUM LANJUT KE CELL 17 ⚠️")
print(f"1. Buka: {config.HUMAN_VALIDATION_FILE}")
print("2. Isi kolom 'human_verdict' MANUAL untuk SEMUA baris:")
print("   'noise' / 'not_noise' / 'ambiguous'")
print("3. Save file (pastikan tersimpan di Drive, bukan di lokal komputer).")
print("4. Jalankan Cell 17 untuk cek kelengkapan + hitung agreement rate.")

📌 Proxy aktif: [3] finetuned_corn — IndoBERT fine-tuned K-Fold, CORN loss (P4) -- DEFAULT/FINAL
🔒 Proxy final terkunci: [3] finetuned_corn
============================================================
 CONFIDENT LEARNING — proxy aktif: [3] finetuned_corn
============================================================
📥 Memuat 9949 baris data train.

🧮 Menghitung OOF pred_probs — proxy [3] finetuned_corn
⚡ Memuat cache proxy [finetuned_corn] ...

📐 Kualitas proxy [finetuned_corn]:
   Exact Accuracy : 0.4596
   MAE            : 0.7939
   Off-by-1 Acc   : 0.8142
   QWK            : 0.6713

🔎 Analisis Metode Filter Cleanlab:
   'confident_learning': 4732 baris diflag (47.56%)
   'prune_by_noise_rate': 4236 baris diflag (42.58%)

🎯 Pemilihan metode filter (kriteria: paling dekat dengan estimasi teoretis terkalibrasi):
   Estimasi teoretis (num_label_issues, off_diagonal_calibrated) : 5441 baris
   'confident_learning': 4732 baris (selisih: 709) <-- DIPILIH
   'prune_by_noise_rate': 4236 baris (selisih: 1205)

✅ Deteksi selesai (metode terpilih: confident_learning).

📊 Distribusi rating_diff pada baris noise (sebelum resolusi):
rating_diff
1    3093
2    1198
3     340
4     101
Name: count, dtype: int64
🗑️  Baris dibuang (rating minoritas dalam grup konflik): 0
🗑️  Baris dibuang (tie, tidak ada mayoritas jelas): 263
   Total dibuang: 263

🗳️  Resolusi konflik teks-identik (voting mayoritas, PASCA-deteksi CL): 9949 -> 9686 baris (dibuang 263)
   Raw (resolved, baseline)     : 9686
   Hard-prune     : buang 4583 / sisa 5103
   Severity-aware : buang 1560 / sisa 8126
📄 Tabel ablasi proxy diperbarui -> /content/drive/MyDrive/SKRIPSI_CORN/results/proxy_ablation_table.csv

💾 Raw (resolved) -> /content/drive/MyDrive/SKRIPSI_CORN/cleaned/train_resolved.csv
💾 Cleaned (hard)   -> /content/drive/MyDrive/SKRIPSI_CORN/cleaned/train_cleaned_hard__finetuned_corn.csv
💾 Cleaned (severe) -> /content/drive/MyDrive/SKRIPSI_CORN/cleaned/train_cleaned_severe__finetuned_corn.csv

📝 Sample validasi manusia (100 baris, BUTA -- predicted_rating/rating_diff TIDAK disertakan):
   /content/drive/MyDrive/SKRIPSI_CORN/human_validation/human_validation_sample__finetuned_corn.csv
   (referensi internal untuk breakdown per-bin -> /content/drive/MyDrive/SKRIPSI_CORN/human_validation/human_validation_internal__finetuned_corn.csv)
   Distribusi rating_diff (internal): {1: 55, 2: 15, 3: 15, 4: 15}
   -> Isi kolom 'human_verdict' manual, lalu jalankan src.human_validation.compute_agreement()
ℹ️  Resolusi konflik teks-identik-rating-beda sekarang otomatis dieksekusi
   di dalam run_confident_learning() SETELAH deteksi CL (Subbab III.D butir 8).

⚠️  BERHENTI DI SINI SEBELUM LANJUT KE CELL 17 ⚠️
1. Buka: /content/drive/MyDrive/SKRIPSI_CORN/human_validation/human_validation_sample__finetuned_corn.csv
2. Isi kolom 'human_verdict' MANUAL untuk SEMUA baris:
   'noise' / 'not_noise' / 'ambiguous'
3. Save file (pastikan tersimpan di Drive, bukan di lokal komputer).
4. Jalankan Cell 17 untuk cek kelengkapan + hitung agreement rate.

## Hitung Agreement Rate Validasi Manusia

Menjalankan **setelah** kamu selesai mengisi `human_verdict` secara manual di
file yang disebut Cell 16. Melaporkan agreement rate keseluruhan dan per-bin
`rating_diff` — breakdown per-bin ini penting sebagai bukti kualitatif
pendukung/penolak asumsi ambang severity-aware pruning (Subbab 3.7).

In [9]:
from src import config
import pandas as pd

df_check = pd.read_csv(config.HUMAN_VALIDATION_FILE, sep=None, engine="python")
print(df_check.shape)
print(df_check["human_verdict"].value_counts(dropna=False))

(100, 7)
human_verdict
not_noise    60
noise        26
ambiguous    14
Name: count, dtype: int64

In [10]:
# ==========================================================
# CELL 18: HITUNG AGREEMENT VALIDASI MANUSIA
# ==========================================================
from src.human_validation import compute_agreement

result = compute_agreement()
if result is not None:
    print("\n✅ Validasi manusia lengkap. Siap lanjut ke Cell 19 (training).")
else:
    print("\n⛔ Belum lengkap/ada error -- perbaiki dulu sebelum lanjut.")

   (file dibaca dengan delimiter ',')
============================================================
 HASIL VALIDASI MANUSIA vs CLEANLAB
============================================================
Total sample direview : 100
Setuju (memang noise) : 26 (26.0%)
Ambigu                : 14 (14.0%)
Tidak setuju          : 60 (60.0%)

📊 Agreement rate per rating_diff:
   diff=1: n=55 | noise=10.9% | not_noise=81.8% | ambiguous=7.3%
   diff=2: n=15 | noise=6.7% | not_noise=53.3% | ambiguous=40.0%
   diff=3: n=15 | noise=53.3% | not_noise=26.7% | ambiguous=20.0%
   diff=4: n=15 | noise=73.3% | not_noise=20.0% | ambiguous=6.7%
------------------------------------------------------------
Acuan pembanding (Northcutt et al., 2021, ImageNet): ~58% sample
yang direview terbukti benar-benar issue -- acuan wajar, bukan standar mutlak.
============================================================

💾 Hasil lengkap -> /content/drive/MyDrive/SKRIPSI_CORN/human_validation/human_validation_result__finetuned_corn.csv

✅ Validasi manusia lengkap. Siap lanjut ke Cell 19 (training).

## Training 6 Skenario × 3 Seed

Melatih 6 skenario (kombinasi 3 varian data × 2 fungsi loss): M1-M3 (raw/
hard-prune/severity-prune × Cross-Entropy), M4-M6 (raw/hard-prune/severity-prune
× CORN). Setiap skenario dilatih pada 3 seed (42, 123, 2024) dengan
mixed-precision training dan early stopping (berhenti kalau Val MAE tidak
membaik 3 epoch berturut-turut).

Auto-resume: kalau sesi Colab terputus, jalankan ulang cell ini — training
akan melanjutkan dari skenario/seed terakhir yang belum selesai, bukan mulai
dari nol.

⏱️ Ini cell paling lama di seluruh notebook — bisa beberapa jam tergantung GPU
yang dialokasikan Colab.

In [11]:
# ==========================================================
# CELL 20: TRAINING 6 SKENARIO x 3 SEED (AUTO-RESUME)
# ==========================================================
import json
import numpy as np
from src.train import run_experiment
from src import config

print(f"🔧 Training M1-M6 akan pakai backbone: {config.PRETRAINED_MODEL_NAME} | "
      f"proxy final: {config.PROXY_NAME}")

scenarios = [
    {"name": "M1_Baseline_CE",        "train_path": config.TRAIN_RAW_RESOLVED_FILE, "loss": "ce"},
    {"name": "M2_CleanedHard_CE",     "train_path": config.TRAIN_CLEANED_HARD_FILE, "loss": "ce"},
    {"name": "M3_CleanedSevere_CE",   "train_path": config.TRAIN_CLEANED_SEVERE_FILE, "loss": "ce"},
    {"name": "M4_Baseline_CORN",      "train_path": config.TRAIN_RAW_RESOLVED_FILE, "loss": "corn"},
    {"name": "M5_CleanedHard_CORN",   "train_path": config.TRAIN_CLEANED_HARD_FILE, "loss": "corn"},
    {"name": "M6_CleanedSevere_CORN", "train_path": config.TRAIN_CLEANED_SEVERE_FILE, "loss": "corn"},
]

if os.path.exists(config.PROGRESS_FILE):
    with open(config.PROGRESS_FILE) as f:
        saved_progress = json.load(f)
    print("🔄 Progress sebelumnya ditemukan, melanjutkan yang belum selesai...")
else:
    saved_progress = {}
    print("🆕 Memulai training dari awal...")

all_results = []
print(f"\n🔥 {len(scenarios)} SKENARIO x {len(config.SEED_LIST)} SEED 🔥\n")

for scenario in scenarios:
    name = scenario["name"]
    metrics_list = {"mae": [], "rmse": [], "accuracy": [], "off_by_one": [], "qwk": []}
    saved_progress.setdefault(name, {})

    for seed in config.SEED_LIST:
        seed_key = str(seed)
        if seed_key in saved_progress[name]:
            print(f"⏩ {name} | seed {seed} (sudah selesai)")
            metrics = saved_progress[name][seed_key]
        else:
            metrics = run_experiment(name, scenario["train_path"], scenario["loss"], seed)
            saved_progress[name][seed_key] = metrics
            with open(config.PROGRESS_FILE, "w") as f:
                json.dump(saved_progress, f, indent=2)

        for k in metrics_list:
            metrics_list[k].append(metrics[k])

    all_results.append({
        "Model": name,
        "MAE (↓)": f"{np.mean(metrics_list['mae']):.4f} ± {np.std(metrics_list['mae']):.4f}",
        "RMSE (↓)": f"{np.mean(metrics_list['rmse']):.4f} ± {np.std(metrics_list['rmse']):.4f}",
        "Acc (↑)": f"{np.mean(metrics_list['accuracy']):.4f} ± {np.std(metrics_list['accuracy']):.4f}",
        "Off-by-1 (↑)": f"{np.mean(metrics_list['off_by_one']):.4f} ± {np.std(metrics_list['off_by_one']):.4f}",
        "QWK (↑)": f"{np.mean(metrics_list['qwk']):.4f} ± {np.std(metrics_list['qwk']):.4f}",
        "_raw_mae": np.mean(metrics_list["mae"]),
    })

df_final = pd.DataFrame(sorted(all_results, key=lambda x: x["_raw_mae"])).drop(columns=["_raw_mae"])
df_final.to_csv(config.FINAL_RESULTS_TABLE_FILE, index=False)

print("\n" + "=" * 100)
print(" 🏆 HASIL 6 SKENARIO (untuk Bab 4) 🏆")
print("=" * 100)
display(df_final)

🔧 Training M1-M6 akan pakai backbone: indobenchmark/indobert-base-p1 | proxy final: finetuned_corn
🆕 Memulai training dari awal...

🔥 6 SKENARIO x 3 SEED 🔥


🚀 M1_Baseline_CE | Seed: 42 | Loss: CE

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Epoch 1/10 - Loss: 1.3595 - Val MAE: 0.8121 | QWK: 0.6829 | Off-by-1: 0.7994 | Acc: 0.4597
Epoch 2/10 - Loss: 1.1865 - Val MAE: 0.7768 | QWK: 0.7000 | Off-by-1: 0.8164 | Acc: 0.4647
Epoch 3/10 - Loss: 1.0140 - Val MAE: 0.7910 | QWK: 0.6749 | Off-by-1: 0.8143 | Acc: 0.4689
Epoch 4/10 - Loss: 0.7815 - Val MAE: 0.7747 | QWK: 0.6803 | Off-by-1: 0.8305 | Acc: 0.4386
Epoch 5/10 - Loss: 0.5031 - Val MAE: 0.7726 | QWK: 0.6763 | Off-by-1: 0.8475 | Acc: 0.4223
Epoch 6/10 - Loss: 0.2976 - Val MAE: 0.8023 | QWK: 0.6612 | Off-by-1: 0.8227 | Acc: 0.4287
Epoch 7/10 - Loss: 0.1710 - Val MAE: 0.7846 | QWK: 0.6671 | Off-by-1: 0.8291 | Acc: 0.4294
Epoch 8/10 - Loss: 0.0965 - Val MAE: 0.8037 | QWK: 0.6544 | Off-by-1: 0.8305 | Acc: 0.4181
   ⏹ Early stopping di epoch 8 (Val MAE tidak membaik 3x)
🏆 Test (checkpoint QWK terbaik=0.7000, tie-break MAE=0.7768): MAE=0.7574 | RMSE=1.1663 | Acc=0.4702 | Off-by-1=0.8323 | QWK=0.7094

🚀 M1_Baseline_CE | Seed: 123 | Loss: CE

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Epoch 1/10 - Loss: 1.3651 - Val MAE: 0.8079 | QWK: 0.6730 | Off-by-1: 0.7938 | Acc: 0.4675
Epoch 2/10 - Loss: 1.1881 - Val MAE: 0.8164 | QWK: 0.6757 | Off-by-1: 0.7903 | Acc: 0.4696
Epoch 3/10 - Loss: 1.0087 - Val MAE: 0.7839 | QWK: 0.6728 | Off-by-1: 0.8256 | Acc: 0.4336
Epoch 4/10 - Loss: 0.7550 - Val MAE: 0.7959 | QWK: 0.6689 | Off-by-1: 0.8326 | Acc: 0.4258
Epoch 5/10 - Loss: 0.4706 - Val MAE: 0.7966 | QWK: 0.6682 | Off-by-1: 0.8107 | Acc: 0.4393
Epoch 6/10 - Loss: 0.2666 - Val MAE: 0.8143 | QWK: 0.6564 | Off-by-1: 0.8150 | Acc: 0.4103
   ⏹ Early stopping di epoch 6 (Val MAE tidak membaik 3x)
🏆 Test (checkpoint QWK terbaik=0.6757, tie-break MAE=0.8164): MAE=0.7693 | RMSE=1.1951 | Acc=0.4811 | Off-by-1=0.8141 | QWK=0.7101

🚀 M1_Baseline_CE | Seed: 2024 | Loss: CE

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Epoch 1/10 - Loss: 1.3490 - Val MAE: 0.7740 | QWK: 0.6801 | Off-by-1: 0.8397 | Acc: 0.4364
Epoch 2/10 - Loss: 1.1828 - Val MAE: 0.8573 | QWK: 0.6661 | Off-by-1: 0.7775 | Acc: 0.4513
Epoch 3/10 - Loss: 1.0173 - Val MAE: 0.7994 | QWK: 0.6759 | Off-by-1: 0.8065 | Acc: 0.4619
Epoch 4/10 - Loss: 0.7731 - Val MAE: 0.7931 | QWK: 0.6729 | Off-by-1: 0.8171 | Acc: 0.4449
   ⏹ Early stopping di epoch 4 (Val MAE tidak membaik 3x)
🏆 Test (checkpoint QWK terbaik=0.6801, tie-break MAE=0.7740): MAE=0.7570 | RMSE=1.1249 | Acc=0.4415 | Off-by-1=0.8466 | QWK=0.6979

🚀 M2_CleanedHard_CE | Seed: 42 | Loss: CE

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Epoch 1/10 - Loss: 1.0306 - Val MAE: 0.8213 | QWK: 0.6577 | Off-by-1: 0.8143 | Acc: 0.4428
Epoch 2/10 - Loss: 0.6253 - Val MAE: 0.8100 | QWK: 0.6726 | Off-by-1: 0.8008 | Acc: 0.4555
Epoch 3/10 - Loss: 0.3763 - Val MAE: 0.7712 | QWK: 0.6813 | Off-by-1: 0.8333 | Acc: 0.4499
Epoch 4/10 - Loss: 0.2111 - Val MAE: 0.7705 | QWK: 0.6875 | Off-by-1: 0.8199 | Acc: 0.4626
Epoch 5/10 - Loss: 0.1078 - Val MAE: 0.7641 | QWK: 0.6992 | Off-by-1: 0.8355 | Acc: 0.4499
Epoch 6/10 - Loss: 0.0642 - Val MAE: 0.7408 | QWK: 0.7103 | Off-by-1: 0.8432 | Acc: 0.4562
Epoch 7/10 - Loss: 0.0320 - Val MAE: 0.7366 | QWK: 0.7081 | Off-by-1: 0.8489 | Acc: 0.4541
Epoch 8/10 - Loss: 0.0205 - Val MAE: 0.7451 | QWK: 0.7039 | Off-by-1: 0.8383 | Acc: 0.4626
Epoch 9/10 - Loss: 0.0103 - Val MAE: 0.7429 | QWK: 0.7051 | Off-by-1: 0.8453 | Acc: 0.4555
Epoch 10/10 - Loss: 0.0074 - Val MAE: 0.7479 | QWK: 0.7024 | Off-by-1: 0.8397 | Acc: 0.4590
   ⏹ Early stopping di epoch 10 (Val MAE tidak membaik 3x)
🏆 Test (checkpoint QWK terbaik=0.7103, tie-break MAE=0.7408): MAE=0.7188 | RMSE=1.1037 | Acc=0.4727 | Off-by-1=0.8557 | QWK=0.7164

🚀 M2_CleanedHard_CE | Seed: 123 | Loss: CE

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Epoch 1/10 - Loss: 1.0666 - Val MAE: 0.7853 | QWK: 0.6779 | Off-by-1: 0.8305 | Acc: 0.4379
Epoch 2/10 - Loss: 0.6385 - Val MAE: 0.7641 | QWK: 0.6880 | Off-by-1: 0.8291 | Acc: 0.4597
Epoch 3/10 - Loss: 0.3934 - Val MAE: 0.7627 | QWK: 0.6926 | Off-by-1: 0.8347 | Acc: 0.4562
Epoch 4/10 - Loss: 0.2244 - Val MAE: 0.7451 | QWK: 0.7105 | Off-by-1: 0.8397 | Acc: 0.4590
Epoch 5/10 - Loss: 0.1140 - Val MAE: 0.7924 | QWK: 0.6909 | Off-by-1: 0.8143 | Acc: 0.4506
Epoch 6/10 - Loss: 0.0584 - Val MAE: 0.7662 | QWK: 0.6986 | Off-by-1: 0.8298 | Acc: 0.4477
Epoch 7/10 - Loss: 0.0373 - Val MAE: 0.7705 | QWK: 0.6917 | Off-by-1: 0.8312 | Acc: 0.4421
   ⏹ Early stopping di epoch 7 (Val MAE tidak membaik 3x)
🏆 Test (checkpoint QWK terbaik=0.7105, tie-break MAE=0.7451): MAE=0.7356 | RMSE=1.1244 | Acc=0.4650 | Off-by-1=0.8519 | QWK=0.7110

🚀 M2_CleanedHard_CE | Seed: 2024 | Loss: CE

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Epoch 1/10 - Loss: 1.0532 - Val MAE: 0.7542 | QWK: 0.7062 | Off-by-1: 0.8432 | Acc: 0.4343
Epoch 2/10 - Loss: 0.6432 - Val MAE: 0.7507 | QWK: 0.7093 | Off-by-1: 0.8404 | Acc: 0.4541
Epoch 3/10 - Loss: 0.3843 - Val MAE: 0.7549 | QWK: 0.7015 | Off-by-1: 0.8340 | Acc: 0.4590
Epoch 4/10 - Loss: 0.2289 - Val MAE: 0.7401 | QWK: 0.7048 | Off-by-1: 0.8369 | Acc: 0.4760
Epoch 5/10 - Loss: 0.1022 - Val MAE: 0.7599 | QWK: 0.6993 | Off-by-1: 0.8234 | Acc: 0.4633
Epoch 6/10 - Loss: 0.0560 - Val MAE: 0.7472 | QWK: 0.7037 | Off-by-1: 0.8347 | Acc: 0.4612
Epoch 7/10 - Loss: 0.0370 - Val MAE: 0.7479 | QWK: 0.7021 | Off-by-1: 0.8376 | Acc: 0.4583
   ⏹ Early stopping di epoch 7 (Val MAE tidak membaik 3x)
🏆 Test (checkpoint QWK terbaik=0.7093, tie-break MAE=0.7507): MAE=0.7335 | RMSE=1.1213 | Acc=0.4664 | Off-by-1=0.8505 | QWK=0.7125

🚀 M3_CleanedSevere_CE | Seed: 42 | Loss: CE

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Epoch 1/10 - Loss: 1.2135 - Val MAE: 0.8376 | QWK: 0.6638 | Off-by-1: 0.7888 | Acc: 0.4428
Epoch 2/10 - Loss: 0.9590 - Val MAE: 0.7295 | QWK: 0.7046 | Off-by-1: 0.8425 | Acc: 0.4710
Epoch 3/10 - Loss: 0.7575 - Val MAE: 0.7556 | QWK: 0.6955 | Off-by-1: 0.8333 | Acc: 0.4626
Epoch 4/10 - Loss: 0.5515 - Val MAE: 0.7585 | QWK: 0.6919 | Off-by-1: 0.8319 | Acc: 0.4605
Epoch 5/10 - Loss: 0.3608 - Val MAE: 0.7521 | QWK: 0.6930 | Off-by-1: 0.8475 | Acc: 0.4400
   ⏹ Early stopping di epoch 5 (Val MAE tidak membaik 3x)
🏆 Test (checkpoint QWK terbaik=0.7046, tie-break MAE=0.7295): MAE=0.7118 | RMSE=1.0989 | Acc=0.4786 | Off-by-1=0.8564 | QWK=0.7166

🚀 M3_CleanedSevere_CE | Seed: 123 | Loss: CE

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Epoch 1/10 - Loss: 1.2210 - Val MAE: 0.7726 | QWK: 0.6909 | Off-by-1: 0.8312 | Acc: 0.4470
Epoch 2/10 - Loss: 0.9562 - Val MAE: 0.7429 | QWK: 0.7077 | Off-by-1: 0.8319 | Acc: 0.4760
Epoch 3/10 - Loss: 0.7617 - Val MAE: 0.8100 | QWK: 0.6826 | Off-by-1: 0.7959 | Acc: 0.4626
Epoch 4/10 - Loss: 0.5588 - Val MAE: 0.7556 | QWK: 0.6976 | Off-by-1: 0.8376 | Acc: 0.4470
Epoch 5/10 - Loss: 0.3471 - Val MAE: 0.7648 | QWK: 0.6830 | Off-by-1: 0.8425 | Acc: 0.4379
   ⏹ Early stopping di epoch 5 (Val MAE tidak membaik 3x)
🏆 Test (checkpoint QWK terbaik=0.7077, tie-break MAE=0.7429): MAE=0.7293 | RMSE=1.1251 | Acc=0.4755 | Off-by-1=0.8470 | QWK=0.7177

🚀 M3_CleanedSevere_CE | Seed: 2024 | Loss: CE

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Epoch 1/10 - Loss: 1.2093 - Val MAE: 0.7874 | QWK: 0.6773 | Off-by-1: 0.8355 | Acc: 0.4174
Epoch 2/10 - Loss: 0.9474 - Val MAE: 0.7797 | QWK: 0.6914 | Off-by-1: 0.8199 | Acc: 0.4597
Epoch 3/10 - Loss: 0.7623 - Val MAE: 0.7422 | QWK: 0.7026 | Off-by-1: 0.8581 | Acc: 0.4407
Epoch 4/10 - Loss: 0.5460 - Val MAE: 0.7818 | QWK: 0.6806 | Off-by-1: 0.8192 | Acc: 0.4492
Epoch 5/10 - Loss: 0.3393 - Val MAE: 0.7634 | QWK: 0.6912 | Off-by-1: 0.8249 | Acc: 0.4576
Epoch 6/10 - Loss: 0.2031 - Val MAE: 0.7648 | QWK: 0.6874 | Off-by-1: 0.8482 | Acc: 0.4280
   ⏹ Early stopping di epoch 6 (Val MAE tidak membaik 3x)
🏆 Test (checkpoint QWK terbaik=0.7026, tie-break MAE=0.7422): MAE=0.7402 | RMSE=1.1039 | Acc=0.4475 | Off-by-1=0.8540 | QWK=0.7069

🚀 M4_Baseline_CORN | Seed: 42 | Loss: CORN

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Epoch 1/10 - Loss: 0.5374 - Val MAE: 0.7401 | QWK: 0.7018 | Off-by-1: 0.8404 | Acc: 0.4527
Epoch 2/10 - Loss: 0.4616 - Val MAE: 0.7288 | QWK: 0.7113 | Off-by-1: 0.8552 | Acc: 0.4548
Epoch 3/10 - Loss: 0.3972 - Val MAE: 0.7373 | QWK: 0.6982 | Off-by-1: 0.8531 | Acc: 0.4506
Epoch 4/10 - Loss: 0.3055 - Val MAE: 0.7775 | QWK: 0.6611 | Off-by-1: 0.8383 | Acc: 0.4294
Epoch 5/10 - Loss: 0.2084 - Val MAE: 0.7627 | QWK: 0.6854 | Off-by-1: 0.8369 | Acc: 0.4357
   ⏹ Early stopping di epoch 5 (Val MAE tidak membaik 3x)
🏆 Test (checkpoint QWK terbaik=0.7113, tie-break MAE=0.7288): MAE=0.7062 | RMSE=1.0640 | Acc=0.4611 | Off-by-1=0.8697 | QWK=0.7272

🚀 M4_Baseline_CORN | Seed: 123 | Loss: CORN

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Epoch 1/10 - Loss: 0.5377 - Val MAE: 0.7528 | QWK: 0.6946 | Off-by-1: 0.8644 | Acc: 0.4153
Epoch 2/10 - Loss: 0.4625 - Val MAE: 0.7239 | QWK: 0.7202 | Off-by-1: 0.8623 | Acc: 0.4541
Epoch 3/10 - Loss: 0.3950 - Val MAE: 0.7514 | QWK: 0.6902 | Off-by-1: 0.8496 | Acc: 0.4350
Epoch 4/10 - Loss: 0.3073 - Val MAE: 0.7662 | QWK: 0.6841 | Off-by-1: 0.8347 | Acc: 0.4244
Epoch 5/10 - Loss: 0.2129 - Val MAE: 0.7549 | QWK: 0.6937 | Off-by-1: 0.8411 | Acc: 0.4555
   ⏹ Early stopping di epoch 5 (Val MAE tidak membaik 3x)
🏆 Test (checkpoint QWK terbaik=0.7202, tie-break MAE=0.7239): MAE=0.7034 | RMSE=1.0708 | Acc=0.4681 | Off-by-1=0.8694 | QWK=0.7300

🚀 M4_Baseline_CORN | Seed: 2024 | Loss: CORN

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Epoch 1/10 - Loss: 0.5393 - Val MAE: 0.7521 | QWK: 0.6948 | Off-by-1: 0.8573 | Acc: 0.4181
Epoch 2/10 - Loss: 0.4638 - Val MAE: 0.7323 | QWK: 0.7124 | Off-by-1: 0.8489 | Acc: 0.4492
Epoch 3/10 - Loss: 0.3977 - Val MAE: 0.7182 | QWK: 0.7183 | Off-by-1: 0.8651 | Acc: 0.4520
Epoch 4/10 - Loss: 0.3038 - Val MAE: 0.7585 | QWK: 0.6919 | Off-by-1: 0.8475 | Acc: 0.4357
Epoch 5/10 - Loss: 0.2059 - Val MAE: 0.8114 | QWK: 0.6496 | Off-by-1: 0.8093 | Acc: 0.4386
Epoch 6/10 - Loss: 0.1288 - Val MAE: 0.7952 | QWK: 0.6731 | Off-by-1: 0.8199 | Acc: 0.4336
   ⏹ Early stopping di epoch 6 (Val MAE tidak membaik 3x)
🏆 Test (checkpoint QWK terbaik=0.7183, tie-break MAE=0.7182): MAE=0.6922 | RMSE=1.0497 | Acc=0.4685 | Off-by-1=0.8764 | QWK=0.7270

🚀 M5_CleanedHard_CORN | Seed: 42 | Loss: CORN

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Epoch 1/10 - Loss: 0.4491 - Val MAE: 0.7648 | QWK: 0.6991 | Off-by-1: 0.8291 | Acc: 0.4583
Epoch 2/10 - Loss: 0.2629 - Val MAE: 0.7556 | QWK: 0.7016 | Off-by-1: 0.8418 | Acc: 0.4470
Epoch 3/10 - Loss: 0.1702 - Val MAE: 0.7331 | QWK: 0.7109 | Off-by-1: 0.8418 | Acc: 0.4619
Epoch 4/10 - Loss: 0.1050 - Val MAE: 0.7338 | QWK: 0.7121 | Off-by-1: 0.8439 | Acc: 0.4661
Epoch 5/10 - Loss: 0.0585 - Val MAE: 0.7352 | QWK: 0.7120 | Off-by-1: 0.8425 | Acc: 0.4689
Epoch 6/10 - Loss: 0.0412 - Val MAE: 0.7641 | QWK: 0.6983 | Off-by-1: 0.8298 | Acc: 0.4605
   ⏹ Early stopping di epoch 6 (Val MAE tidak membaik 3x)
🏆 Test (checkpoint QWK terbaik=0.7121, tie-break MAE=0.7338): MAE=0.7202 | RMSE=1.1015 | Acc=0.4727 | Off-by-1=0.8519 | QWK=0.7188

🚀 M5_CleanedHard_CORN | Seed: 123 | Loss: CORN

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Epoch 1/10 - Loss: 0.4451 - Val MAE: 0.8573 | QWK: 0.6566 | Off-by-1: 0.7804 | Acc: 0.4449
Epoch 2/10 - Loss: 0.2601 - Val MAE: 0.7260 | QWK: 0.7190 | Off-by-1: 0.8489 | Acc: 0.4590
Epoch 3/10 - Loss: 0.1721 - Val MAE: 0.7782 | QWK: 0.6919 | Off-by-1: 0.8284 | Acc: 0.4470
Epoch 4/10 - Loss: 0.1031 - Val MAE: 0.7924 | QWK: 0.6880 | Off-by-1: 0.8199 | Acc: 0.4513
Epoch 5/10 - Loss: 0.0609 - Val MAE: 0.7422 | QWK: 0.7102 | Off-by-1: 0.8545 | Acc: 0.4442
   ⏹ Early stopping di epoch 5 (Val MAE tidak membaik 3x)
🏆 Test (checkpoint QWK terbaik=0.7190, tie-break MAE=0.7260): MAE=0.7164 | RMSE=1.0879 | Acc=0.4664 | Off-by-1=0.8592 | QWK=0.7192

🚀 M5_CleanedHard_CORN | Seed: 2024 | Loss: CORN

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Epoch 1/10 - Loss: 0.4488 - Val MAE: 0.7775 | QWK: 0.6978 | Off-by-1: 0.8390 | Acc: 0.4336
Epoch 2/10 - Loss: 0.2660 - Val MAE: 0.7514 | QWK: 0.7007 | Off-by-1: 0.8404 | Acc: 0.4463
Epoch 3/10 - Loss: 0.1720 - Val MAE: 0.7648 | QWK: 0.6999 | Off-by-1: 0.8347 | Acc: 0.4506
Epoch 4/10 - Loss: 0.1010 - Val MAE: 0.7571 | QWK: 0.7010 | Off-by-1: 0.8376 | Acc: 0.4527
Epoch 5/10 - Loss: 0.0589 - Val MAE: 0.7316 | QWK: 0.7141 | Off-by-1: 0.8496 | Acc: 0.4597
Epoch 6/10 - Loss: 0.0386 - Val MAE: 0.7429 | QWK: 0.7055 | Off-by-1: 0.8411 | Acc: 0.4626
Epoch 7/10 - Loss: 0.0228 - Val MAE: 0.7585 | QWK: 0.7055 | Off-by-1: 0.8340 | Acc: 0.4513
Epoch 8/10 - Loss: 0.0154 - Val MAE: 0.7507 | QWK: 0.7029 | Off-by-1: 0.8355 | Acc: 0.4562
   ⏹ Early stopping di epoch 8 (Val MAE tidak membaik 3x)
🏆 Test (checkpoint QWK terbaik=0.7141, tie-break MAE=0.7316): MAE=0.7332 | RMSE=1.1067 | Acc=0.4569 | Off-by-1=0.8564 | QWK=0.7132

🚀 M6_CleanedSevere_CORN | Seed: 42 | Loss: CORN

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Epoch 1/10 - Loss: 0.4930 - Val MAE: 0.7910 | QWK: 0.6898 | Off-by-1: 0.8256 | Acc: 0.4379
Epoch 2/10 - Loss: 0.3793 - Val MAE: 0.7493 | QWK: 0.7081 | Off-by-1: 0.8362 | Acc: 0.4562
Epoch 3/10 - Loss: 0.2990 - Val MAE: 0.7564 | QWK: 0.6968 | Off-by-1: 0.8376 | Acc: 0.4463
Epoch 4/10 - Loss: 0.2213 - Val MAE: 0.7239 | QWK: 0.7092 | Off-by-1: 0.8552 | Acc: 0.4569
Epoch 5/10 - Loss: 0.1474 - Val MAE: 0.7415 | QWK: 0.7035 | Off-by-1: 0.8439 | Acc: 0.4597
Epoch 6/10 - Loss: 0.0987 - Val MAE: 0.7387 | QWK: 0.7033 | Off-by-1: 0.8552 | Acc: 0.4456
Epoch 7/10 - Loss: 0.0652 - Val MAE: 0.7323 | QWK: 0.7069 | Off-by-1: 0.8595 | Acc: 0.4463
   ⏹ Early stopping di epoch 7 (Val MAE tidak membaik 3x)
🏆 Test (checkpoint QWK terbaik=0.7092, tie-break MAE=0.7239): MAE=0.7199 | RMSE=1.0762 | Acc=0.4538 | Off-by-1=0.8645 | QWK=0.7113

🚀 M6_CleanedSevere_CORN | Seed: 123 | Loss: CORN

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Epoch 1/10 - Loss: 0.4966 - Val MAE: 0.8121 | QWK: 0.6841 | Off-by-1: 0.8001 | Acc: 0.4470
Epoch 2/10 - Loss: 0.3799 - Val MAE: 0.7422 | QWK: 0.7104 | Off-by-1: 0.8496 | Acc: 0.4513
Epoch 3/10 - Loss: 0.3031 - Val MAE: 0.7408 | QWK: 0.7004 | Off-by-1: 0.8468 | Acc: 0.4463
Epoch 4/10 - Loss: 0.2293 - Val MAE: 0.7352 | QWK: 0.7115 | Off-by-1: 0.8524 | Acc: 0.4470
Epoch 5/10 - Loss: 0.1562 - Val MAE: 0.7373 | QWK: 0.7029 | Off-by-1: 0.8588 | Acc: 0.4393
Epoch 6/10 - Loss: 0.0979 - Val MAE: 0.7564 | QWK: 0.6896 | Off-by-1: 0.8517 | Acc: 0.4308
Epoch 7/10 - Loss: 0.0645 - Val MAE: 0.7634 | QWK: 0.6886 | Off-by-1: 0.8538 | Acc: 0.4230
   ⏹ Early stopping di epoch 7 (Val MAE tidak membaik 3x)
🏆 Test (checkpoint QWK terbaik=0.7115, tie-break MAE=0.7352): MAE=0.7286 | RMSE=1.0967 | Acc=0.4552 | Off-by-1=0.8599 | QWK=0.7079

🚀 M6_CleanedSevere_CORN | Seed: 2024 | Loss: CORN

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Epoch 1/10 - Loss: 0.4941 - Val MAE: 0.7500 | QWK: 0.7071 | Off-by-1: 0.8439 | Acc: 0.4506
Epoch 2/10 - Loss: 0.3814 - Val MAE: 0.7401 | QWK: 0.7078 | Off-by-1: 0.8432 | Acc: 0.4612
Epoch 3/10 - Loss: 0.3056 - Val MAE: 0.7458 | QWK: 0.7043 | Off-by-1: 0.8453 | Acc: 0.4470
Epoch 4/10 - Loss: 0.2222 - Val MAE: 0.7599 | QWK: 0.6919 | Off-by-1: 0.8489 | Acc: 0.4315
Epoch 5/10 - Loss: 0.1474 - Val MAE: 0.7479 | QWK: 0.7021 | Off-by-1: 0.8468 | Acc: 0.4435
   ⏹ Early stopping di epoch 5 (Val MAE tidak membaik 3x)
🏆 Test (checkpoint QWK terbaik=0.7078, tie-break MAE=0.7401): MAE=0.7188 | RMSE=1.0864 | Acc=0.4629 | Off-by-1=0.8589 | QWK=0.7252

====================================================================================================
 🏆 HASIL 6 SKENARIO (untuk Bab 4) 🏆
====================================================================================================

,Model,MAE (↓),RMSE (↓),Acc (↑),Off-by-1 (↑),QWK (↑)
0,M4_Baseline_CORN,0.7006 ± 0.0061,1.0615 ± 0.0088,0.4659 ± 0.0034,0.8718 ± 0.0032,0.7281 ± 0.0014
1,M6_CleanedSevere_CORN,0.7225 ± 0.0044,1.0864 ± 0.0084,0.4573 ± 0.0040,0.8611 ± 0.0024,0.7148 ± 0.0075
2,M5_CleanedHard_CORN,0.7233 ± 0.0072,1.0987 ± 0.0079,0.4653 ± 0.0065,0.8559 ± 0.0030,0.7171 ± 0.0027
3,M3_CleanedSevere_CE,0.7271 ± 0.0117,1.1093 ± 0.0113,0.4672 ± 0.0140,0.8525 ± 0.0040,0.7137 ± 0.0048
4,M2_CleanedHard_CE,0.7293 ± 0.0075,1.1165 ± 0.0091,0.4680 ± 0.0034,0.8527 ± 0.0022,0.7133 ± 0.0023
5,M1_Baseline_CE,0.7612 ± 0.0057,1.1621 ± 0.0288,0.4643 ± 0.0167,0.8310 ± 0.0133,0.7058 ± 0.0056

## Uji Signifikansi — Wilcoxon + Holm-Bonferroni (5 Hipotesis) + CI Bootstrap QWK
H1: CORN vs CE pada data mentah (M4 vs M1)
H2: severity-aware vs baseline pada CORN (M6 vs M4)
H3: hard-prune vs baseline pada CORN (M5 vs M4)
H4: severity-aware vs hard-prune langsung (M6 vs M5)
H5: severity-aware vs baseline pada CE (M3 vs M1) — apakah manfaat cleaning
    selektif spesifik pada arsitektur ordinal, atau berlaku umum lintas fungsi loss
QWK adalah metrik keputusan utama tapi tidak bisa diuji Wilcoxon (dihitung
atas matriks konfusi agregat) — dilaporkan via CI bootstrap terpisah (III.I.2).

In [12]:
# ==========================================================
# CELL 22: UJI SIGNIFIKANSI -- WILCOXON+HOLM-BONFERRONI (5 HIPOTESIS) + CI QWK
# ==========================================================
from src.significance import (
    collect_all_predictions, aggregate_errors_across_seeds,
    run_significance_test, run_all_effect_sizes, run_all_qwk_effect_sizes,
)
from src import config

print("📥 Mengumpulkan prediksi dari 3 seed x 6 skenario...")
true_labels, preds_per_seed = collect_all_predictions(scenarios)

aggregated_errors = aggregate_errors_across_seeds(true_labels, preds_per_seed)

print("\n🔬 Wilcoxon Signed-Rank (H1-H5) + Holm-Bonferroni...")
sig_results = run_significance_test(aggregated_errors)
display(sig_results)

print("\n📐 Effect size MAE + CI 95% (pelengkap Wilcoxon)...")
effect_sizes = run_all_effect_sizes(aggregated_errors)
display(effect_sizes)
effect_sizes.to_csv(os.path.join(config.RESULTS_DIR, "effect_sizes.csv"), index=False)

print("\n📐 Selisih QWK + CI 95% bootstrap (metrik keputusan utama, TANPA Wilcoxon)...")
qwk_effect_sizes = run_all_qwk_effect_sizes(true_labels, preds_per_seed)
display(qwk_effect_sizes)
qwk_effect_sizes.to_csv(os.path.join(config.RESULTS_DIR, "qwk_effect_sizes.csv"), index=False)

📥 Mengumpulkan prediksi dari 3 seed x 6 skenario...
   Memuat prediksi M1_Baseline_CE | seed 42 ...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

   Memuat prediksi M1_Baseline_CE | seed 123 ...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

   Memuat prediksi M1_Baseline_CE | seed 2024 ...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

   Memuat prediksi M2_CleanedHard_CE | seed 42 ...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

   Memuat prediksi M2_CleanedHard_CE | seed 123 ...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

   Memuat prediksi M2_CleanedHard_CE | seed 2024 ...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

   Memuat prediksi M3_CleanedSevere_CE | seed 42 ...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

   Memuat prediksi M3_CleanedSevere_CE | seed 123 ...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

   Memuat prediksi M3_CleanedSevere_CE | seed 2024 ...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

   Memuat prediksi M4_Baseline_CORN | seed 42 ...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

   Memuat prediksi M4_Baseline_CORN | seed 123 ...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

   Memuat prediksi M4_Baseline_CORN | seed 2024 ...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

   Memuat prediksi M5_CleanedHard_CORN | seed 42 ...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

   Memuat prediksi M5_CleanedHard_CORN | seed 123 ...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

   Memuat prediksi M5_CleanedHard_CORN | seed 2024 ...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

   Memuat prediksi M6_CleanedSevere_CORN | seed 42 ...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

   Memuat prediksi M6_CleanedSevere_CORN | seed 123 ...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

   Memuat prediksi M6_CleanedSevere_CORN | seed 2024 ...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

🔬 Wilcoxon Signed-Rank (H1-H5) + Holm-Bonferroni...

💾 Hasil uji signifikansi (5 hipotesis, Holm-Bonferroni) -> /content/drive/MyDrive/SKRIPSI_CORN/results/significance_test.csv

,hypothesis,model_a,model_b,mean_error_a,mean_error_b,p_value_raw,p_value_corrected,signifikan
0,H1_CORN_vs_CE_raw,M4_Baseline_CORN,M1_Baseline_CE,0.700630,0.761204,2.983634e-12,1.491817e-11,Ya
1,H2_SeverityAware_vs_Base,M6_CleanedSevere_CORN,M4_Baseline_CORN,0.722456,0.700630,4.259827e-03,8.519654e-03,Ya
2,H3_HardPrune_vs_Base,M5_CleanedHard_CORN,M4_Baseline_CORN,0.723273,0.700630,2.462054e-03,7.386163e-03,Ya
3,H4_SeverityAware_vs_Hard,M6_CleanedSevere_CORN,M5_CleanedHard_CORN,0.722456,0.723273,9.919289e-01,9.919289e-01,Tidak
4,H5_SeverityAware_vs_Base_CE,M3_CleanedSevere_CE,M1_Baseline_CE,0.727124,0.761204,1.011453e-05,4.045814e-05,Ya

📐 Effect size MAE + CI 95% (pelengkap Wilcoxon)...

,model_a,model_b,mean_diff,ci_95_low,ci_95_high
0,M4_Baseline_CORN,M1_Baseline_CE,-0.060574,-0.075864,-0.045743
1,M6_CleanedSevere_CORN,M4_Baseline_CORN,0.021825,0.009454,0.033847
2,M5_CleanedHard_CORN,M4_Baseline_CORN,0.022642,0.008754,0.036064
3,M6_CleanedSevere_CORN,M5_CleanedHard_CORN,-0.000817,-0.014122,0.013658
4,M3_CleanedSevere_CE,M1_Baseline_CE,-0.034080,-0.049023,-0.019725

📐 Selisih QWK + CI 95% bootstrap (metrik keputusan utama, TANPA Wilcoxon)...

,model_a,model_b,qwk_a,qwk_b,qwk_diff,ci_95_low,ci_95_high
0,M4_Baseline_CORN,M1_Baseline_CE,0.735904,0.734088,0.001815,-0.007278,0.010757
1,M6_CleanedSevere_CORN,M4_Baseline_CORN,0.725690,0.735904,-0.010213,-0.018618,-0.001387
2,M5_CleanedHard_CORN,M4_Baseline_CORN,0.726271,0.735904,-0.009632,-0.019049,-0.000521
3,M6_CleanedSevere_CORN,M5_CleanedHard_CORN,0.725690,0.726271,-0.000581,-0.010394,0.008885
4,M3_CleanedSevere_CE,M1_Baseline_CE,0.725385,0.734088,-0.008703,-0.018097,0.000561

## Ringkasan Akhir — Siap Disalin ke Bab 1 (Pilot Study) dan Bab 4

Semua dibaca dari file di Drive (bukan variabel session), jadi cell ini bisa
dijalankan kapan saja, tidak peduli cell mana yang sudah/belum jalan di sesi
Colab saat ini.

In [ ]:
# ==========================================================
# CELL 24: RINGKASAN AKHIR
# ==========================================================
import os
import pandas as pd
from src import config

print("=" * 70)
print(" RINGKASAN LENGKAP ")
print("=" * 70)

print("\n[1] TABEL ABLASI PROXY (P1-P4) -- untuk Bab 1 (pilot study) & Bab 4:")
if os.path.exists(config.PROXY_QUALITY_LOG_FILE):
    display(pd.read_csv(config.PROXY_QUALITY_LOG_FILE))
else:
    print("   ⚠️ Belum ada -- jalankan Cell 12 dulu.")

print("\n[2] LAPORAN KUALITAS DATA SCRAPING -- untuk Bab 3:")
for fname in ["scraping_summary.csv", "date_distribution_per_app_rating.csv",
              "text_length_summary.csv", "duplicate_review_texts.csv"]:
    fpath = os.path.join(config.RESULTS_DIR, fname)
    status = "✅" if os.path.exists(fpath) else "⚠️ belum ada"
    print(f"   {status} {fpath}")

print("\n[3] VALIDASI MANUSIA -- untuk Bab 4:")
if os.path.exists(config.HUMAN_VALIDATION_RESULT_FILE):
    df_human = pd.read_csv(config.HUMAN_VALIDATION_RESULT_FILE)
    counts = df_human["human_verdict"].value_counts()
    total = len(df_human)
    print(f"   Total: {total} | Noise: {counts.get('noise',0)} ({counts.get('noise',0)/total*100:.1f}%) "
          f"| Not noise: {counts.get('not_noise',0)} ({counts.get('not_noise',0)/total*100:.1f}%) "
          f"| Ambiguous: {counts.get('ambiguous',0)} ({counts.get('ambiguous',0)/total*100:.1f}%)")
else:
    print("   ⚠️ Belum ada -- jalankan Cell 18 dulu.")

print("\n[4] HASIL 6 SKENARIO (Mean ± Std, 3 seed) -- untuk Bab 4:")
if os.path.exists(config.FINAL_RESULTS_TABLE_FILE):
    display(pd.read_csv(config.FINAL_RESULTS_TABLE_FILE))
else:
    print("   ⚠️ Belum ada -- jalankan Cell 20 dulu.")

print("\n[5] UJI SIGNIFIKANSI (4 hipotesis pre-registered) -- untuk Bab 4:")
if os.path.exists(config.SIGNIFICANCE_TEST_FILE):
    display(pd.read_csv(config.SIGNIFICANCE_TEST_FILE))
else:
    print("   ⚠️ Belum ada -- jalankan Cell 22 dulu.")

print("\n[6] EFFECT SIZE + CI 95% -- untuk Bab 4:")
effect_size_file = os.path.join(config.RESULTS_DIR, "effect_sizes.csv")
if os.path.exists(effect_size_file):
    display(pd.read_csv(effect_size_file))
else:
    print("   ⚠️ Belum ada -- jalankan Cell 22 dulu.")

print("\n[7] EFFECT SIZE QWK + CI 95% -- untuk Bab 4:")
qwk_file = os.path.join(config.RESULTS_DIR, "qwk_effect_sizes.csv")
if os.path.exists(qwk_file):
    display(pd.read_csv(qwk_file))
else:
    print("   ⚠️ Belum ada -- jalankan Cell 22 dulu.")

print("\n✅ Semua file hasil tersimpan di:", config.RESULTS_DIR)